import type {
  AccessTier,
  Control,
  IndustryDefinition,
  Pillar,
  StandardDefinition,
  StandardKind,
} from "./types";

const controlTemplates: Array<{
  name: string;
  category: string;
  pillars: Pillar[];
  remediation: string;
}> = [
  {
    name: "AI risk assessment and treatment",
    category: "Governance",
    pillars: ["governance", "compliance"],
    remediation: "Document the system risk assessment, owner, treatment plan, and review cadence.",
  },
  {
    name: "Access control and least privilege",
    category: "Security",
    pillars: ["security", "governance"],
    remediation: "Enforce role-based access, least privilege, and quarterly entitlement reviews.",
  },
  {
    name: "Encryption and key management",
    category: "Technical safeguards",
    pillars: ["security", "data_protection"],
    remediation: "Use managed encryption at rest and TLS 1.2+ with documented key rotation.",
  },
  {
    name: "Privacy, minimisation, and retention",
    category: "Data lifecycle",
    pillars: ["data_protection", "compliance"],
    remediation: "Minimise indexed data, redact sensitive values, and enforce a tested retention schedule.",
  },
  {
    name: "Human oversight and escalation",
    category: "Trustworthiness",
    pillars: ["trust", "governance"],
    remediation: "Add named human oversight, appeal, escalation, and safe shutdown procedures.",
  },
  {
    name: "Accuracy and groundedness monitoring",
    category: "Trustworthiness",
    pillars: ["trust"],
    remediation: "Measure retrieval precision, groundedness, and hallucination rates against acceptance thresholds.",
  },
  {
    name: "Bias and adverse-impact testing",
    category: "Fairness",
    pillars: ["trust", "compliance"],
    remediation: "Test outcomes by relevant protected groups and document mitigation and re-test results.",
  },
  {
    name: "Logging, monitoring, and incident response",
    category: "Operations",
    pillars: ["security", "compliance"],
    remediation: "Centralise immutable audit logs and test the AI incident and breach response runbook.",
  },
  {
    name: "Supplier and model-provider assurance",
    category: "Third-party risk",
    pillars: ["governance", "compliance"],
    remediation: "Record supplier due diligence, contractual controls, and ongoing service assurance.",
  },
  {
    name: "Model card and system documentation",
    category: "Documentation",
    pillars: ["governance", "trust"],
    remediation: "Maintain a current model card covering intended use, limits, data, evaluation, and change history.",
  },
  {
    name: "RAG corpus integrity and provenance",
    category: "Data assurance",
    pillars: ["security", "trust", "data_protection"],
    remediation: "Verify source provenance, signed ingestion, tenant isolation, and poisoning detection.",
  },
  {
    name: "Transparency and user notice",
    category: "Transparency",
    pillars: ["trust", "compliance"],
    remediation: "Tell users when AI is used, its limits, data practices, and available human review routes.",
  },
];

function buildControls(prefix: string, total: number, coverage: [number, number, number]): Control[] {
  return Array.from({ length: total }, (_, index) => {
    const template = controlTemplates[index % controlTemplates.length];
    const ordinal = index + 1;
    const tierMinimum: AccessTier =
      ordinal <= coverage[0] ? 1 : ordinal <= coverage[1] ? 2 : 3;
    return {
      id: `${prefix}-${String(ordinal).padStart(2, "0")}`,
      name: template.name,
      category: template.category,
      pillars: template.pillars,
      tierMinimum,
      testType:
        tierMinimum === 1
          ? "adversarial_probe"
          : tierMinimum === 2
            ? "config_check"
            : "document_verify",
      remediation: template.remediation,
    };
  });
}

type StandardSeed = Omit<StandardDefinition, "controls" | "coverage" | "officialReference"> & {
  total: number;
  coverage: [number, number, number];
  prefix: string;
};

const officialReferences: Record<string, StandardDefinition["officialReference"]> = {
  hipaa: {
    authority: "U.S. Department of Health and Human Services",
    title: "HIPAA Security Rule",
    url: "https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html",
    status: "current",
    note: "Official regulator summary and links to the governing regulations.",
  },
  iso42001: {
    authority: "International Organization for Standardization",
    title: "ISO/IEC 42001:2023",
    url: "https://www.iso.org/standard/42001",
    status: "licensed_preview",
    note: "Official ISO catalog and preview; the complete standard is licensed.",
  },
  nist_ai_rmf: {
    authority: "National Institute of Standards and Technology",
    title: "AI Risk Management Framework",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    status: "under_revision",
    note: "Official NIST framework page; AI RMF 1.0 is currently being revised.",
  },
  mas_ai: {
    authority: "Monetary Authority of Singapore",
    title: "FEAT Principles",
    url: "https://www.mas.gov.sg/-/media/mas/news-and-publications/monographs-and-information-papers/feat-principles-updated-7-feb-19.pdf",
    status: "current",
    note: "Official MAS publication URL; the MAS site may occasionally show maintenance.",
  },
  sr_11_7: {
    authority: "Board of Governors of the Federal Reserve System",
    title: "SR 26-2 Revised Guidance on Model Risk Management",
    url: "https://www.federalreserve.gov/supervisionreg/srletters/SR2602.htm",
    status: "superseded",
    note: "SR 26-2 superseded SR 11-7 on April 17, 2026; the catalog retains the legacy selection label for continuity.",
  },
  soc2: {
    authority: "AICPA & CIMA",
    title: "SOC 2 Reporting Guide",
    url: "https://www.aicpa-cima.com/cpe-learning/publication/soc-2-reporting-on-an-examination-of-controls-at-a-service-organization-relevant-to-security-availability-processing-integrity-confidentiality-or-privacy-OPL",
    status: "licensed_preview",
    note: "Official AICPA publication page; detailed Trust Services Criteria content is licensed.",
  },
  naic: {
    authority: "National Association of Insurance Commissioners",
    title: "Model Bulletin on the Use of AI Systems by Insurers",
    url: "https://content.naic.org/sites/default/files/cmte-h-big-data-artificial-intelligence-wg-ai-model-bulletin.pdf.pdf",
    status: "current",
    note: "Official adopted model bulletin; applicability depends on state adoption.",
  },
  eu_ai_act: {
    authority: "EUR-Lex",
    title: "Regulation (EU) 2024/1689 — Artificial Intelligence Act",
    url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en",
    status: "current",
    note: "Official Journal text of the EU Artificial Intelligence Act.",
  },
  nyc_ll144: {
    authority: "New York City Department of Consumer and Worker Protection",
    title: "Automated Employment Decision Tools",
    url: "https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page",
    status: "current",
    note: "Official NYC enforcement, rule, FAQ, and notice resources.",
  },
  colorado_ai_act: {
    authority: "Colorado General Assembly",
    title: "SB24-205 Consumer Protections for Artificial Intelligence",
    url: "https://leg.colorado.gov/bills/sb24-205",
    status: "current",
    note: "Official bill history and enrolled legislation.",
  },
  ferpa: {
    authority: "U.S. Department of Education",
    title: "What is FERPA?",
    url: "https://studentprivacy.ed.gov/faq/what-ferpa",
    status: "current",
    note: "Official Student Privacy Policy Office guidance.",
  },
  unece_ads: {
    authority: "United Nations Economic Commission for Europe",
    title: "Framework document on automated/autonomous vehicles",
    url: "https://unece.org/transport/publications/framework-document-automatedautonomous-vehicles-updated",
    status: "current",
    note: "Official UNECE automated-driving framework publication.",
  },
  iso21448: {
    authority: "International Organization for Standardization",
    title: "ISO 21448:2022",
    url: "https://www.iso.org/standard/77490.html",
    status: "licensed_preview",
    note: "Official ISO catalog and preview; the complete standard is licensed.",
  },
  uk_av_act: {
    authority: "The National Archives, United Kingdom",
    title: "Automated Vehicles Act 2024",
    url: "https://www.legislation.gov.uk/ukpga/2024/10/contents/enacted",
    status: "current",
    note: "Official enacted legislation.",
  },
  cepej: {
    authority: "Council of Europe CEPEJ",
    title: "European Ethical Charter on AI in Judicial Systems",
    url: "https://www.coe.int/en/web/cepej/cepej-european-ethical-charter-on-the-use-of-artificial-intelligence-ai-in-judicial-systems-and-their-environment",
    status: "current",
    note: "Official CEPEJ charter and supporting material.",
  },
  canada_aia: {
    authority: "Treasury Board of Canada Secretariat",
    title: "Directive on Automated Decision-Making",
    url: "https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32592",
    status: "current",
    note: "Official directive governing federal automated administrative decisions.",
  },
  eu_machinery: {
    authority: "EUR-Lex",
    title: "Regulation (EU) 2023/1230 on machinery",
    url: "https://eur-lex.europa.eu/eli/reg/2023/1230/oj?locale=en",
    status: "current",
    note: "Official Journal text and consolidated versions.",
  },
  iec62443: {
    authority: "International Electrotechnical Commission",
    title: "IEC 62443-2-4:2023",
    url: "https://webstore.iec.ch/en/publication/67631",
    status: "licensed_preview",
    note: "Official IEC catalog entry representing the IEC 62443 series; complete standards are licensed.",
  },
  iso13849: {
    authority: "International Organization for Standardization",
    title: "ISO 13849-1:2023",
    url: "https://www.iso.org/standard/73481.html",
    status: "licensed_preview",
    note: "Official ISO catalog and preview; the complete standard is licensed.",
  },
  china_deep_synthesis: {
    authority: "Cyberspace Administration of China",
    title: "Provisions on Deep Synthesis Internet Information Services",
    url: "https://www.cac.gov.cn/2022-12/11/c_1672221949354811.htm",
    status: "current",
    note: "Official Chinese-language regulatory text.",
  },
  c2pa: {
    authority: "Coalition for Content Provenance and Authenticity",
    title: "C2PA Specifications",
    url: "https://spec.c2pa.org/specifications/",
    status: "current",
    note: "Official technical specifications and implementation guidance.",
  },
  omb_m_24_10: {
    authority: "U.S. Office of Management and Budget",
    title: "M-25-21 Accelerating Federal Use of AI",
    url: "https://www.whitehouse.gov/wp-content/uploads/2025/02/M-25-21-Accelerating-Federal-Use-of-AI-through-Innovation-Governance-and-Public-Trust.pdf",
    status: "superseded",
    note: "M-25-21 replaced the M-24-10 federal AI governance policy in April 2025; the catalog retains the legacy selection label for continuity.",
  },
  netherlands_iama: {
    authority: "Government of the Netherlands — Digital Government",
    title: "Impact Assessment Human Rights and Algorithms (IAMA)",
    url: "https://www.digitaleoverheid.nl/nieuws/iama-aangepast-aan-praktijk-en-regelgeving/",
    status: "current",
    note: "Official government notice for the updated 2026 IAMA aligned with EU AI Act Article 27.",
  },
};

const officialSectionLocators: Record<string, string[]> = {
  hipaa: [
    "45 CFR §164.308(a)(1) Security management process",
    "45 CFR §164.308(a)(4) Information access management",
    "45 CFR §164.312(a) and (e) Access and transmission security",
    "45 CFR §164.316(b) Documentation retention and availability",
    "45 CFR §164.308(a)(2) Assigned security responsibility",
    "45 CFR §164.308(a)(8) Evaluation",
    "45 CFR §164.308(a)(1)(ii)(A) Risk analysis",
    "45 CFR §164.308(a)(6) Security incident procedures",
    "45 CFR §164.308(b) Business associate arrangements",
    "45 CFR §164.316 Policies, procedures, and documentation",
    "45 CFR §164.312(c) Integrity",
    "45 CFR §164.312(d) Person or entity authentication",
  ],
  iso42001: ["Clauses 4–10", "Annex A.2–A.10"],
  nist_ai_rmf: ["GOVERN function", "MAP function", "MEASURE function", "MANAGE function"],
  mas_ai: ["Fairness principle", "Ethics principle", "Accountability principle", "Transparency principle"],
  sr_11_7: ["SR 26-2: Governance", "SR 26-2: Model development, implementation, and use", "SR 26-2: Model validation"],
  soc2: ["Trust Services Criteria CC1–CC9", "Availability A1", "Confidentiality C1", "Privacy P1–P8"],
  naic: ["Model Bulletin Section 1", "Model Bulletin Section 2", "Model Bulletin Section 3", "Model Bulletin Section 4"],
  eu_ai_act: ["Articles 9–15", "Articles 26–27", "Articles 43 and 49–50"],
  nyc_ll144: ["NYC Administrative Code §§20-870–20-874", "Rules of the City of New York §5-300 et seq."],
  colorado_ai_act: ["Colorado Revised Statutes §§6-1-1701–1707"],
  ferpa: ["34 CFR §§99.3, 99.30–99.37"],
  unece_ads: ["UNECE automated/autonomous vehicles framework document"],
  iso21448: ["ISO 21448:2022 Clauses 4–12"],
  uk_av_act: ["Automated Vehicles Act 2024 Parts 1–7"],
  cepej: ["CEPEJ Charter: five ethical principles"],
  canada_aia: ["Directive on Automated Decision-Making Sections 4–6", "Directive appendices B–D"],
  eu_machinery: ["Regulation (EU) 2023/1230 Articles 10–18", "Regulation (EU) 2023/1230 Annex III"],
  iec62443: ["IEC 62443-2-1", "IEC 62443-2-4", "IEC 62443-3-2", "IEC 62443-3-3", "IEC 62443-4-1", "IEC 62443-4-2"],
  iso13849: ["ISO 13849-1:2023 Clauses 4–11"],
  china_deep_synthesis: ["Deep Synthesis Provisions Articles 4–17"],
  c2pa: ["C2PA Technical Specification: trust model, manifests, assertions, and validation"],
  omb_m_24_10: ["OMB M-25-21 Sections 1–5 and implementation appendix"],
  netherlands_iama: ["IAMA 2026 human-rights impact assessment modules"],
};

const standardSeeds: StandardSeed[] = [
  {
    id: "hipaa",
    shortName: "HIPAA",
    name: "Health Insurance Portability and Accountability Act",
    version: "45 CFR Parts 160, 162, 164",
    kind: "Mandatory",
    jurisdiction: "United States",
    description: "Administrative, technical, and physical safeguards for protected health information.",
    reportFormat: "HIPAA Safeguard Assessment",
    scoringMethod: "Equal weight per safeguard category",
    passThreshold: "100% required for regulatory compliance",
    total: 12,
    coverage: [7, 10, 12],
    prefix: "164",
  },
  {
    id: "iso42001",
    shortName: "ISO/IEC 42001",
    name: "Artificial Intelligence Management System",
    version: "ISO/IEC 42001:2023",
    kind: "Certifiable",
    jurisdiction: "Global",
    description: "A certifiable AI management-system standard covering governance and responsible operation.",
    reportFormat: "ISO 42001 Conformity Assessment",
    scoringMethod: "Conforms / Minor NC / Major NC / Not Assessed",
    passThreshold: "Zero major non-conformities",
    total: 38,
    coverage: [22, 32, 38],
    prefix: "A",
  },
  {
    id: "nist_ai_rmf",
    shortName: "NIST AI RMF",
    name: "NIST Artificial Intelligence Risk Management Framework",
    version: "AI RMF 1.0",
    kind: "Methodological",
    jurisdiction: "United States / Global",
    description: "Risk management guidance organised around Govern, Map, Measure, and Manage.",
    reportFormat: "NIST AI RMF Maturity Profile",
    scoringMethod: "Maturity level 1–5 per function",
    passThreshold: "Level 3 or higher recommended",
    total: 27,
    coverage: [15, 23, 27],
    prefix: "RMF",
  },
  {
    id: "mas_ai",
    shortName: "MAS FEAT",
    name: "MAS Fairness, Ethics, Accountability and Transparency Principles",
    version: "FEAT Principles",
    kind: "Mandatory",
    jurisdiction: "Singapore",
    description: "Responsible use of AI and data analytics in financial services.",
    reportFormat: "MAS FEAT Assurance Report",
    scoringMethod: "Principle effectiveness with exceptions",
    passThreshold: "All material principles effective",
    total: 12,
    coverage: [7, 10, 12],
    prefix: "FEAT",
  },
  {
    id: "sr_11_7",
    shortName: "SR 11-7",
    name: "Supervisory Guidance on Model Risk Management",
    version: "SR Letter 11-7",
    kind: "Mandatory",
    jurisdiction: "United States",
    description: "Governance, validation, and controls for models used by banking organisations.",
    reportFormat: "Model Risk Management Review",
    scoringMethod: "Effective / Needs improvement / Deficient",
    passThreshold: "No deficient material controls",
    total: 12,
    coverage: [6, 10, 12],
    prefix: "MRM",
  },
  {
    id: "soc2",
    shortName: "SOC 2 Type II",
    name: "AICPA Trust Services Criteria",
    version: "2017 TSC, revised points of focus",
    kind: "Certifiable",
    jurisdiction: "Global",
    description: "Operational effectiveness of security, availability, confidentiality, and privacy controls.",
    reportFormat: "SOC 2 Control Effectiveness Report",
    scoringMethod: "Effective / Not effective with exceptions",
    passThreshold: "All controls effective",
    total: 17,
    coverage: [8, 15, 17],
    prefix: "CC",
  },
  {
    id: "naic",
    shortName: "NAIC AI Bulletin",
    name: "NAIC Model Bulletin on the Use of AI Systems by Insurers",
    version: "NAIC Model Bulletin 2023",
    kind: "Mandatory",
    jurisdiction: "United States",
    description: "Governance expectations for insurers using AI-supported decisions.",
    reportFormat: "NAIC Insurer AI Governance Report",
    scoringMethod: "Expectation met / gap / not assessed",
    passThreshold: "All adopted regulatory expectations met",
    total: 10,
    coverage: [6, 8, 10],
    prefix: "NAIC",
  },
  {
    id: "eu_ai_act",
    shortName: "EU AI Act",
    name: "European Union Artificial Intelligence Act",
    version: "Regulation (EU) 2024/1689",
    kind: "Mandatory",
    jurisdiction: "European Union",
    description: "Risk-tiered mandatory requirements for AI systems placed on or used in the EU market.",
    reportFormat: "EU AI Act Requirements Checklist",
    scoringMethod: "Mandatory requirement pass/fail",
    passThreshold: "100% for applicable high-risk requirements",
    total: 22,
    coverage: [12, 18, 22],
    prefix: "ART",
  },
  {
    id: "nyc_ll144",
    shortName: "NYC LL144",
    name: "New York City Automated Employment Decision Tools Law",
    version: "Local Law 144 of 2021",
    kind: "Mandatory",
    jurisdiction: "New York City",
    description: "Independent bias audit, notice, and publication duties for automated employment tools.",
    reportFormat: "NYC LL144 Bias Audit Readiness Report",
    scoringMethod: "Four-fifths rule plus disclosures",
    passThreshold: "Selection-rate threshold and all notices met",
    total: 8,
    coverage: [6, 7, 8],
    prefix: "LL144",
  },
  {
    id: "colorado_ai_act",
    shortName: "Colorado AI Act",
    name: "Colorado Artificial Intelligence Act",
    version: "SB24-205",
    kind: "Mandatory",
    jurisdiction: "Colorado, United States",
    description: "Duties for developers and deployers of high-risk AI systems.",
    reportFormat: "Colorado High-Risk AI Impact Report",
    scoringMethod: "Duty met / gap / not applicable",
    passThreshold: "All applicable deployer and developer duties met",
    total: 10,
    coverage: [6, 8, 10],
    prefix: "CO",
  },
  {
    id: "ferpa",
    shortName: "FERPA",
    name: "Family Educational Rights and Privacy Act",
    version: "20 U.S.C. § 1232g; 34 CFR Part 99",
    kind: "Mandatory",
    jurisdiction: "United States",
    description: "Privacy and disclosure requirements for student education records.",
    reportFormat: "FERPA Education Records Safeguard Report",
    scoringMethod: "Requirement met / unmet",
    passThreshold: "All applicable privacy requirements met",
    total: 10,
    coverage: [6, 8, 10],
    prefix: "FERPA",
  },
  {
    id: "unece_ads",
    shortName: "UNECE ADS",
    name: "UNECE Automated Driving Systems Regulation",
    version: "UNECE ADS regulatory framework",
    kind: "Mandatory",
    jurisdiction: "UNECE contracting parties",
    description: "Safety, operational, and audit requirements for automated driving systems.",
    reportFormat: "UNECE ADS Safety Case",
    scoringMethod: "Safety requirement conformity",
    passThreshold: "No unresolved safety-critical non-conformities",
    total: 12,
    coverage: [6, 10, 12],
    prefix: "ADS",
  },
  {
    id: "iso21448",
    shortName: "ISO 21448 SOTIF",
    name: "Safety of the Intended Functionality",
    version: "ISO 21448:2022",
    kind: "Certifiable",
    jurisdiction: "Global",
    description: "Hazards caused by functional insufficiencies in road-vehicle systems.",
    reportFormat: "SOTIF Safety Assessment",
    scoringMethod: "Hazard control conformity",
    passThreshold: "Residual risk acceptable",
    total: 12,
    coverage: [6, 10, 12],
    prefix: "SOTIF",
  },
  {
    id: "uk_av_act",
    shortName: "UK AV Act",
    name: "Automated Vehicles Act 2024",
    version: "UK Public General Act 2024",
    kind: "Mandatory",
    jurisdiction: "United Kingdom",
    description: "Self-driving authorisation, responsibility, and safety requirements.",
    reportFormat: "UK AV Authorisation Readiness Report",
    scoringMethod: "Authorisation requirement met / gap",
    passThreshold: "All safety-critical duties met",
    total: 10,
    coverage: [5, 8, 10],
    prefix: "UKAV",
  },
  {
    id: "cepej",
    shortName: "CEPEJ Charter",
    name: "European Ethical Charter on the Use of AI in Judicial Systems",
    version: "CEPEJ(2018)14",
    kind: "Methodological",
    jurisdiction: "Council of Europe",
    description: "Fundamental-rights, non-discrimination, quality, transparency, and user-control principles.",
    reportFormat: "CEPEJ Ethical Principles Assessment",
    scoringMethod: "Principle maturity assessment",
    passThreshold: "Mature implementation across five principles",
    total: 10,
    coverage: [6, 8, 10],
    prefix: "CEPEJ",
  },
  {
    id: "canada_aia",
    shortName: "Canada AIA",
    name: "Algorithmic Impact Assessment",
    version: "Directive on Automated Decision-Making",
    kind: "Mandatory",
    jurisdiction: "Canada",
    description: "Impact level, peer review, notice, recourse, and monitoring for automated decisions.",
    reportFormat: "Canada Algorithmic Impact Assessment",
    scoringMethod: "Impact-level requirement checklist",
    passThreshold: "All requirements for the assessed impact level met",
    total: 12,
    coverage: [7, 10, 12],
    prefix: "AIA",
  },
  {
    id: "eu_machinery",
    shortName: "EU Machinery Regulation",
    name: "EU Machinery Regulation",
    version: "Regulation (EU) 2023/1230",
    kind: "Mandatory",
    jurisdiction: "European Union",
    description: "Health, safety, cybersecurity, and conformity requirements for machinery products.",
    reportFormat: "EU Machinery Conformity Report",
    scoringMethod: "Essential requirement conformity",
    passThreshold: "All applicable essential requirements met",
    total: 12,
    coverage: [6, 10, 12],
    prefix: "MR",
  },
  {
    id: "iec62443",
    shortName: "IEC 62443",
    name: "Industrial Automation and Control Systems Security",
    version: "IEC 62443 series",
    kind: "Certifiable",
    jurisdiction: "Global",
    description: "Cybersecurity lifecycle and technical controls for industrial automation systems.",
    reportFormat: "IEC 62443 Security Level Assessment",
    scoringMethod: "Foundational requirement and security-level conformity",
    passThreshold: "Target security level achieved",
    total: 12,
    coverage: [6, 10, 12],
    prefix: "FR",
  },
  {
    id: "iso13849",
    shortName: "ISO 13849",
    name: "Safety of Machinery — Safety-Related Parts of Control Systems",
    version: "ISO 13849-1:2023",
    kind: "Certifiable",
    jurisdiction: "Global",
    description: "Design and validation of safety-related control-system functions.",
    reportFormat: "ISO 13849 Performance Level Report",
    scoringMethod: "Required vs achieved performance level",
    passThreshold: "Achieved PL meets or exceeds required PL",
    total: 10,
    coverage: [5, 8, 10],
    prefix: "PL",
  },
  {
    id: "china_deep_synthesis",
    shortName: "China Deep Synthesis",
    name: "Provisions on the Administration of Deep Synthesis Internet Information Services",
    version: "Effective January 2023",
    kind: "Mandatory",
    jurisdiction: "China",
    description: "Identity, content governance, labelling, security assessment, and record obligations.",
    reportFormat: "Deep Synthesis Service Compliance Report",
    scoringMethod: "Provision conformity checklist",
    passThreshold: "All applicable provider duties met",
    total: 10,
    coverage: [6, 8, 10],
    prefix: "DS",
  },
  {
    id: "c2pa",
    shortName: "C2PA",
    name: "Coalition for Content Provenance and Authenticity Standard",
    version: "C2PA Technical Specification 2.x",
    kind: "Methodological",
    jurisdiction: "Global",
    description: "Cryptographically verifiable provenance and authenticity for digital content.",
    reportFormat: "C2PA Conformance and Provenance Report",
    scoringMethod: "Manifest and validation conformance",
    passThreshold: "Valid, complete, and durable provenance chain",
    total: 10,
    coverage: [5, 8, 10],
    prefix: "C2PA",
  },
  {
    id: "omb_m_24_10",
    shortName: "OMB M-24-10",
    name: "Advancing Governance, Innovation, and Risk Management for Agency Use of AI",
    version: "OMB Memorandum M-24-10",
    kind: "Mandatory",
    jurisdiction: "United States Federal Government",
    description: "Governance and minimum practices for rights- and safety-impacting federal AI.",
    reportFormat: "OMB M-24-10 Agency AI Governance Report",
    scoringMethod: "Minimum-practice conformity",
    passThreshold: "All applicable minimum practices met",
    total: 12,
    coverage: [7, 10, 12],
    prefix: "OMB",
  },
  {
    id: "netherlands_iama",
    shortName: "Netherlands IAMA",
    name: "Impact Assessment for Human Rights and Algorithms",
    version: "IAMA 2.0",
    kind: "Methodological",
    jurisdiction: "Netherlands",
    description: "Human-rights impact assessment for algorithmic systems in the public sector.",
    reportFormat: "IAMA Human Rights Impact Report",
    scoringMethod: "Impact and safeguard maturity",
    passThreshold: "No unmitigated high human-rights impact",
    total: 10,
    coverage: [6, 8, 10],
    prefix: "IAMA",
  },
];

export const standards: StandardDefinition[] = standardSeeds.map((seed) => {
  const { total, coverage, prefix, ...definition } = seed;
  const reference = officialReferences[seed.id];
  const sections = officialSectionLocators[seed.id] ?? [reference.title];
  return {
    ...definition,
    officialReference: reference,
    coverage: { 1: coverage[0], 2: coverage[1], 3: coverage[2] },
    controls: buildControls(prefix, total, coverage).map((control, index) => ({
      ...control,
      sourceCitation: {
        authority: reference.authority,
        document: reference.title,
        section: sections[index % sections.length],
        url: reference.url,
        mappingType: "governai_evidence_mapping" as const,
        note: "GovernAI evidence check mapped to this official section; it is not a verbatim official questionnaire or certification control.",
      },
    })),
  };
});

export const industries: IndustryDefinition[] = [
  {
    id: "healthcare",
    name: "Healthcare",
    description: "Clinical, payer, health-tech, and patient-support systems.",
    recommendations: [
      { standardId: "hipaa", reason: "Mandatory US health-data safeguards" },
      { standardId: "iso42001", reason: "Certifiable AI management system" },
      { standardId: "nist_ai_rmf", reason: "Methodological AI risk practice" },
    ],
  },
  {
    id: "finance",
    name: "Finance / Banking",
    description: "Banks, fintech, payments, wealth, and lending.",
    recommendations: [
      { standardId: "mas_ai", reason: "Financial-sector AI governance" },
      { standardId: "soc2", reason: "Client-trust control assurance" },
      { standardId: "iso42001", reason: "Certifiable AI governance" },
    ],
  },
  {
    id: "insurance",
    name: "Insurance",
    description: "Underwriting, claims, pricing, and policyholder support.",
    recommendations: [
      { standardId: "naic", reason: "Insurance regulator expectations" },
      { standardId: "iso42001", reason: "Certifiable AI management system" },
      { standardId: "eu_ai_act", reason: "EU high-risk AI obligations" },
    ],
  },
  {
    id: "hr",
    name: "HR / Recruitment",
    description: "Hiring, screening, promotion, and workforce analytics.",
    recommendations: [
      { standardId: "nyc_ll144", reason: "Mandatory NYC bias-audit duties" },
      { standardId: "colorado_ai_act", reason: "High-risk employment AI duties" },
      { standardId: "eu_ai_act", reason: "EU employment AI requirements" },
    ],
  },
  {
    id: "education",
    name: "Education",
    description: "Schools, universities, learning platforms, and student services.",
    recommendations: [
      { standardId: "ferpa", reason: "Mandatory student-record privacy" },
      { standardId: "nist_ai_rmf", reason: "Methodological risk management" },
      { standardId: "iso42001", reason: "Certifiable AI governance" },
    ],
  },
  {
    id: "autonomous_vehicles",
    name: "Autonomous Vehicles",
    description: "Automated-driving systems, suppliers, and mobility platforms.",
    recommendations: [
      { standardId: "unece_ads", reason: "Automated-driving regulatory safety" },
      { standardId: "iso21448", reason: "SOTIF safety assurance" },
      { standardId: "uk_av_act", reason: "UK self-driving authorisation" },
    ],
  },
  {
    id: "legal",
    name: "Legal / Judiciary",
    description: "Courts, legal services, case analysis, and justice systems.",
    recommendations: [
      { standardId: "cepej", reason: "Judicial ethical AI principles" },
      { standardId: "eu_ai_act", reason: "EU justice-sector high-risk AI" },
      { standardId: "canada_aia", reason: "Public decision impact assessment" },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    description: "Industrial automation, machinery, quality, and worker safety.",
    recommendations: [
      { standardId: "eu_machinery", reason: "EU machinery conformity" },
      { standardId: "iec62443", reason: "Industrial cybersecurity assurance" },
      { standardId: "iso13849", reason: "Safety-related control systems" },
    ],
  },
  {
    id: "media",
    name: "Media / Content",
    description: "Generative media, publishing, advertising, and content platforms.",
    recommendations: [
      { standardId: "china_deep_synthesis", reason: "Deep-synthesis provider duties" },
      { standardId: "c2pa", reason: "Content provenance best practice" },
      { standardId: "eu_ai_act", reason: "Synthetic-content transparency" },
    ],
  },
  {
    id: "government",
    name: "Government / Public Sector",
    description: "Public services, benefits, enforcement, and civic systems.",
    recommendations: [
      { standardId: "omb_m_24_10", reason: "US federal AI minimum practices" },
      { standardId: "canada_aia", reason: "Automated-decision impact duties" },
      { standardId: "netherlands_iama", reason: "Human-rights impact method" },
    ],
  },
];

export const standardById = new Map(standards.map((standard) => [standard.id, standard]));
export const industryById = new Map(industries.map((industry) => [industry.id, industry]));

export const tierCoverageLabel = (standard: StandardDefinition, tier: AccessTier) =>
  `${standard.coverage[tier]}/${standard.controls.length}`;

export const standardKindOrder: Record<StandardKind, number> = {
  Mandatory: 0,
  Certifiable: 1,
  Methodological: 2,
};
