import { bankingEvidenceRules } from "../banking-evidence";
import { contentHashForControls, createPackControl, validateFrameworkPack, type FrameworkPack } from "./schema";
import type { StandardKind } from "../types";

interface BankingPackSpec {
  id: string;
  shortName: string;
  name: string;
  version: string;
  jurisdiction: string;
  authority: string;
  url: string;
  kind: StandardKind;
  scope: string;
  sourceStatus?: "current" | "under_revision" | "licensed_preview";
  /** Source topics are deliberately used rather than invented clause numbers. */
  topics: Array<[string, string]>;
}

const specs: BankingPackSpec[] = [
  { id: "rbi_it_governance", shortName: "RBI IT Governance", name: "RBI Information Technology Governance, Risk, Controls and Assurance Practices", version: "Directions 2023", jurisdiction: "India", authority: "Reserve Bank of India", url: "https://systemhealth.rbi.org.in/Scripts/BS_ViewMasDirections.aspx_id%3D12562%283%29.html", kind: "Mandatory", scope: "Applicable RBI-regulated entities; bank-wide IT governance, controls, assurance and recovery.", topics: [
    ["board-oversight", "IT governance framework and Board oversight"], ["risk-appetite", "IT risk management"], ["independent-audit", "Information systems audit"], ["asset-inventory", "IT service management and asset controls"], ["privileged-access", "Access controls and segregation of duties"], ["patch-vulnerability", "Change and patch management"], ["secure-development", "Application development and security testing"], ["network-protection", "Information security controls"], ["physical-security", "Physical and environmental controls"], ["security-logging", "Audit trails and monitoring"], ["vendor-contracts", "Third-party agreements"], ["data-lineage", "Data migration controls"], ["critical-operations", "Business continuity management"], ["recovery-testing", "Disaster recovery testing"], ["incident-response", "Incident management"] ] },
  { id: "rbi_it_outsourcing", shortName: "RBI IT Outsourcing", name: "RBI Outsourcing of Information Technology Services", version: "Directions 2023", jurisdiction: "India", authority: "Reserve Bank of India", url: "https://systemhealth.rbi.org.in/Scripts/BS_ViewMasDirections.aspx_id%3D12486%283%29.html", kind: "Mandatory", scope: "Material IT outsourcing, cloud and service-provider arrangements of applicable regulated entities.", topics: [
    ["board-oversight", "Governance framework"], ["vendor-diligence", "Evaluation and due diligence of service providers"], ["vendor-contracts", "Outsourcing agreements and regulatory access"], ["vendor-concentration", "Risk management and concentration risk"], ["vendor-exit", "Exit strategy"], ["cross-border", "Cross-border outsourcing"], ["privileged-access", "Confidentiality and security"], ["security-logging", "Monitoring and control of outsourced activities"], ["critical-operations", "Business continuity planning"], ["recovery-testing", "Recovery and continuity testing"], ["incident-response", "Incident reporting and response"], ["independent-audit", "Audit and assurance"] ] },
  { id: "rbi_digital_payments", shortName: "RBI Digital Payments", name: "RBI Digital Payment Security Controls", version: "Directions 2021", jurisdiction: "India", authority: "Reserve Bank of India", url: "https://systemhealth.rbi.org.in/Scripts/BS_ViewMasDirections.aspx_id%3D12032%283%29.html", kind: "Mandatory", scope: "Digital payments of applicable banks and credit-card issuing NBFCs; select for payment environments.", topics: [
    ["board-oversight", "Governance and management of security risks"], ["payment-authentication", "Authentication framework"], ["payment-fraud", "Fraud risk management"], ["payment-data", "Application and payment-data security"], ["secure-development", "Secure development and security testing"], ["network-protection", "Infrastructure security"], ["security-logging", "Logging and monitoring"], ["vendor-diligence", "Third-party oversight"], ["recovery-testing", "Business continuity and backup testing"], ["incident-response", "Incident response"], ["customer-redress", "Customer protection and grievance redressal"] ] },
  { id: "rbi_kyc_aml", shortName: "RBI KYC / AML", name: "RBI Commercial Banks Know Your Customer and AML Control Readiness", version: "Commercial Banks Directions 2025 / December 2025 baseline", jurisdiction: "India", authority: "Reserve Bank of India", url: "https://www.rbi.org.in/scripts/NotificationUser.aspx?Id=13141", sourceStatus: "under_revision", kind: "Mandatory", scope: "Commercial-bank customer due diligence, financial-crime controls and reporting. Later amendments require source review; other bank types have separate directions.", topics: [
    ["board-oversight", "KYC policy and governance"], ["customer-diligence", "Customer identification, beneficial ownership and periodic updation"], ["pep-sanctions", "Enhanced due diligence, PEPs and sanctions screening"], ["aml-monitoring", "Ongoing due diligence and transaction monitoring"], ["aml-reporting", "Record management and reporting to FIU-IND"], ["independent-audit", "Independent evaluation of KYC and AML controls"] ] },
  { id: "fatf", shortName: "FATF AML / CFT", name: "FATF Recommendations — Institutional AML and CFT Readiness", version: "Recommendations; source review October 2026", jurisdiction: "Global", authority: "Financial Action Task Force", url: "https://www.fatf-gafi.org/en/publications/Fatfrecommendations/Fatf-recommendations.html", kind: "Methodological", scope: "Institutional readiness mappings; country-level implementation and legislation are outside this pack.", topics: [
    ["risk-appetite", "Recommendation 1 — Risk-based approach"], ["customer-diligence", "Recommendations 10 and 24 — Customer due diligence and beneficial ownership"], ["pep-sanctions", "Recommendations 6, 7 and 12 — Targeted sanctions and PEPs"], ["aml-monitoring", "Recommendations 10 and 15 — Ongoing monitoring and new technologies"], ["aml-reporting", "Recommendations 11 and 20 — Records and suspicious transaction reporting"], ["independent-audit", "Recommendation 18 — Internal controls"] ] },
  { id: "rbi_free_ai", shortName: "RBI FREE-AI", name: "RBI Framework for Responsible and Ethical Enablement of Artificial Intelligence", version: "Committee Report August 2025", jurisdiction: "India", authority: "Reserve Bank of India", url: "https://m.rbi.org.in/scripts/bs_viewpublicationreport.aspx", kind: "Methodological", scope: "Financial-sector responsible AI readiness; committee recommendations are guidance, not a certification or a binding direction.", topics: [
    ["board-oversight", "Governance and accountability"], ["risk-appetite", "Risk-based AI governance"], ["model-inventory", "AI lifecycle governance"], ["model-validation", "Assurance and validation"], ["model-drift", "Lifecycle monitoring"], ["ai-fairness", "Fairness, explainability and human oversight"], ["ai-safety", "Safety and responsible deployment"], ["privacy-rights", "Data protection"], ["customer-redress", "Customer protection"], ["vendor-diligence", "Third-party AI governance"], ["incident-response", "AI incident response"] ] },
  { id: "bcbs_239", shortName: "BCBS 239", name: "Principles for Effective Risk Data Aggregation and Risk Reporting", version: "January 2013 principles", jurisdiction: "Global", authority: "Basel Committee on Banking Supervision", url: "https://www.bis.org/publ/bcbs239.pdf", kind: "Methodological", scope: "Bank obligations under Principles 1–11, especially for systemically important banks. Principles 12–14 are supervisory duties.", topics: [
    ["board-oversight", "Principle 1 — Governance"], ["data-lineage", "Principle 2 — Data architecture and IT infrastructure"], ["data-quality", "Principle 3 — Accuracy and integrity"], ["data-quality", "Principle 4 — Completeness"], ["data-timeliness", "Principle 5 — Timeliness"], ["data-timeliness", "Principle 6 — Adaptability"], ["data-quality", "Principle 7 — Accuracy of risk reports"], ["report-distribution", "Principle 8 — Comprehensiveness"], ["report-distribution", "Principle 9 — Clarity and usefulness"], ["data-timeliness", "Principle 10 — Frequency"], ["report-distribution", "Principle 11 — Distribution"] ] },
  { id: "basel_operational_resilience", shortName: "Basel Resilience", name: "Basel Principles for Operational Resilience", version: "March 2021", jurisdiction: "Global", authority: "Basel Committee on Banking Supervision", url: "https://www.bis.org/bcbs/publ/d516.htm", kind: "Methodological", scope: "Seven operational resilience principles applied to a bank's critical operations and dependencies.", topics: [
    ["board-oversight", "Principle 1 — Governance"], ["risk-appetite", "Principle 2 — Operational risk management"], ["recovery-testing", "Principle 3 — Business continuity planning and testing"], ["critical-operations", "Principle 4 — Mapping interconnections and interdependencies"], ["vendor-concentration", "Principle 5 — Third-party dependency management"], ["incident-response", "Principle 6 — Incident management"], ["network-protection", "Principle 7 — ICT including cybersecurity"] ] },
  { id: "basel_core", shortName: "Basel Core Governance", name: "Basel Core Principles — Bank Risk Governance Readiness", version: "April 2024 selected principles", jurisdiction: "Global", authority: "Basel Committee on Banking Supervision", url: "https://www.bis.org/committees/bcbs/basel-framework/standard/bcp/40/inforce/2024-04-25/published/2024-04-25", kind: "Methodological", scope: "Bank-side selected governance objectives. Capital and liquidity measurements reflect bank-owned reviews; this app does not calculate prudential ratios or certify supervisory compliance.", topics: [
    ["board-oversight", "Principle 14 — Corporate governance"], ["risk-appetite", "Principle 15 — Risk management process"], ["model-validation", "Principle 15 — Model understanding and validation"], ["prudential-risk", "Principles 16 and 24 — Capital adequacy and liquidity risk"], ["credit-decisions", "Principle 17 — Credit risk"], ["independent-audit", "Principle 26 — Internal control and audit"], ["regulatory-reporting", "Principle 28 — Disclosure and transparency"] ] },
  { id: "swift_cscf", shortName: "SWIFT CSCF", name: "SWIFT Customer Security Controls Framework Readiness", version: "v2026 topic mapping", jurisdiction: "Global / SWIFT users", authority: "SWIFT", url: "https://www.swift.com/myswift/customer-security-programme/understand-controls", kind: "Methodological", scope: "Public objective-level readiness mapping. Detailed architecture-specific mandatory/advisory controls and independent attestation require the licensed CSCF and assessor review.", topics: [
    ["swift-isolation", "Secure your environment"], ["privileged-access", "Know and limit access"], ["physical-security", "Secure your environment — physical security"], ["patch-vulnerability", "Secure your environment — reduce attack surface"], ["swift-integrity", "Detect and respond — transaction integrity"], ["security-logging", "Detect and respond — monitoring"], ["incident-response", "Detect and respond — incident response"], ["swift-attestation", "Independent assessment and annual attestation"] ] },
  { id: "nist_csf", shortName: "NIST CSF 2.0", name: "NIST Cybersecurity Framework", version: "2.0 / February 2024", jurisdiction: "Global", authority: "National Institute of Standards and Technology", url: "https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20", kind: "Methodological", scope: "Authored checks across all six CSF functions; these are selected outcomes rather than the entire CSF subcategory catalogue.", topics: [
    ["board-oversight", "GV.RR — Roles, responsibilities and authorities"], ["risk-appetite", "GV.RM — Risk management strategy"], ["vendor-diligence", "GV.SC — Cybersecurity supply chain risk management"], ["asset-inventory", "ID.AM — Asset management"], ["patch-vulnerability", "ID.RA — Risk assessment"], ["privileged-access", "PR.AA — Identity management, authentication and access control"], ["data-protection", "PR.DS — Data security"], ["network-protection", "PR.PS — Platform security"], ["security-logging", "DE.CM — Continuous monitoring"], ["incident-response", "RS.MA — Incident management"], ["recovery-testing", "RC.RP — Incident recovery plan execution"] ] },
  { id: "iso22301", shortName: "ISO 22301", name: "ISO Security and Resilience — Business Continuity Management Systems", version: "2019 / Amd 1:2024", jurisdiction: "Global", authority: "International Organization for Standardization", url: "https://www.iso.org/standard/75106.html", kind: "Certifiable", scope: "Selected BCMS readiness objectives; certification requires the licensed standard and independent audit.", topics: [
    ["critical-operations", "Context and business impact analysis"], ["board-oversight", "Leadership and policy"], ["risk-appetite", "Planning and risk assessment"], ["vendor-concentration", "Continuity strategies and dependencies"], ["incident-response", "Continuity procedures and communication"], ["recovery-testing", "Exercise programme and recovery"], ["independent-audit", "Performance evaluation and improvement"] ] },
  { id: "sr_11_7", shortName: "SR 26-2", name: "Revised Guidance on Model Risk Management", version: "SR 26-2 / April 2026", jurisdiction: "United States", authority: "Board of Governors of the Federal Reserve System", url: "https://www.federalreserve.gov/supervisionreg/srletters/sr2602.htm", kind: "Methodological", scope: "US banking model-risk readiness. Legacy selection ID retained. Separate responsible-AI packs cover generative and agentic AI.", topics: [
    ["board-oversight", "Model risk governance"], ["risk-appetite", "Risk-based approach and effective challenge"], ["model-inventory", "Model inventory and materiality"], ["model-validation", "Model development, use and validation"], ["model-drift", "Ongoing monitoring and outcomes analysis"], ["vendor-diligence", "Vendor models"], ["credit-decisions", "Model use and limitations"] ] },
];

const pillarFor: Record<string, "trust" | "security" | "governance" | "compliance" | "data_protection"> = {
  "Board and assurance": "governance", "Cybersecurity and access": "security", "Outsourcing and cloud": "governance", "Privacy and customer protection": "data_protection", "AI and model risk": "trust", "Risk data and reporting": "compliance", "Resilience and recovery": "governance", "Payments and SWIFT": "security", "AML, KYC and sanctions": "compliance", "Prudential and credit risk": "governance",
};

export const bankingFrameworkPacks: FrameworkPack[] = specs.map(spec => {
  const source = { authority: spec.authority, title: `${spec.name} — ${spec.version}`, url: spec.url, status: spec.sourceStatus ?? "current" as const, note: spec.scope };
  const controls = spec.topics.map(([key, section], index) => {
    const evidence = bankingEvidenceRules.find(rule => rule.key === key);
    if (!evidence) throw new Error(`Unknown banking evidence rule ${key}`);
    return createPackControl({
      id: `${spec.id.toUpperCase()}-${String(index + 1).padStart(2, "0")}`,
      name: evidence.name, category: evidence.domain,
      objective: `Evaluate ${section} using ${evidence.system}. Required checks: ${Object.entries(evidence.fields).map(([field, condition]) => `${field} must be ${condition === "true" ? "true" : condition === "zero" ? "zero" : "positive"}`).join("; ")}.`,
      tierMinimum: 3, pillars: [pillarFor[evidence.domain]], testType: "document_verify",
      evaluationRuleId: `artifact.bank-${key}`, evidenceProcedureIds: [`artifact-bank-${key}`],
      severity: /privileged|patch|payment|swift|aml|sanctions|validation|recovery|data-quality|credit/.test(key) ? "critical" : "high",
      section, mappingType: "governai_evidence_mapping", remediationId: `bank-${key}`,
      remediation: `Resolve failed ${evidence.name.toLowerCase()} checks with the accountable control owner, retain the corrective-action record, and publish fresh evidence from ${evidence.system}.`,
    }, source);
  });
  return validateFrameworkPack({
    manifest: { id: spec.id, release: "2026.10-draft.1", status: "draft", assuranceLevel: "readiness", sourceVersion: spec.version, publishedAt: "2026-10-09", contentHash: contentHashForControls(controls), note: `${spec.scope} Every listed control requires named Tier 3 evidence. Coverage describes listed objectives, not regulatory completeness.` },
    standard: { id: spec.id, shortName: spec.shortName, name: spec.name, version: spec.version, kind: spec.kind, jurisdiction: spec.jurisdiction, description: spec.scope, reportFormat: `${spec.shortName} Governance Readiness Report`, scoringMethod: "Measured control outcomes and named evidence — pass, fail, partial or not assessed", passThreshold: "No open material weaknesses; required evidence supplied", officialReference: source },
    controls,
  });
});
