import { contentHashForControls, createPackControl, validateFrameworkPack, type FrameworkPack, type PackControlInput } from "./schema";

const source = {
  authority: "EUR-Lex",
  title: "Regulation (EU) 2024/1689 — Artificial Intelligence Act",
  url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en",
  status: "current" as const,
  note: "Official Journal text. Applicability and enforcement dates must be evaluated as of the assessment date.",
};
const c = (input: PackControlInput) => createPackControl(input, source);
const legal = { mappingType: "official_requirement" as const };

/* Every obligation listed applies to every assessed system and the pack asks no
   scope questions. It lists only obligations a Tier 3 run can reach a verdict on;
   prohibited-practice screening, deployer and FRIA duties, AI-interaction
   disclosure, provider QMS and corrective action, importer and distributor
   checks, conformity, declaration, registration and GPAI duties are out of scope. */
const controls = [
  c({ ...legal, id: "EUAIA-GOV-01", name: "AI literacy", objective: "Personnel and others operating AI on the organization's behalf have sufficient literacy for their role, context, and affected persons.", category: "Governance", tierMinimum: 3, pillars: ["governance", "trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.training", severity: "high", section: "Article 4", evidenceProcedureIds: ["document-training-program", "artifact-training-completion"], remediationId: "eu-ai-literacy", remediation: "Provide role- and context-specific AI literacy training and retain completion and effectiveness evidence." }),
  c({ ...legal, id: "EUAIA-HR-01", name: "Risk management system", objective: "High-risk AI risks are identified, analyzed, evaluated, treated, tested, and reviewed throughout the lifecycle.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["governance", "trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.risk-management-system", severity: "critical", section: "Article 9", evidenceProcedureIds: ["document-risk-register", "document-risk-treatment", "artifact-test-plan"], remediationId: "eu-risk-management", remediation: "Establish a continuous high-risk AI risk management process with testing and residual-risk acceptance." }),
  c({ ...legal, id: "EUAIA-HR-02", name: "Data and data governance", objective: "Training, validation, testing, and retrieval data are governed for relevance, representativeness, quality, provenance, bias, and appropriate scope.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["data_protection", "trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.data-governance", severity: "critical", section: "Article 10", evidenceProcedureIds: ["artifact-data-lineage", "artifact-rag-corpus-manifest", "artifact-bias-evaluation"], remediationId: "eu-data-governance", remediation: "Implement governed datasets and corpus manifests with provenance, quality, bias, authorization, and limitation records." }),
  c({ ...legal, id: "EUAIA-HR-03", name: "Technical documentation", objective: "Technical documentation demonstrates system purpose, design, capabilities, limits, testing, risks, controls, and lifecycle changes.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.technical-documentation", severity: "critical", section: "Article 11 and Annex IV", evidenceProcedureIds: ["document-system-card", "artifact-technical-file"], remediationId: "eu-technical-file", remediation: "Maintain an Annex IV-aligned technical file linked to versions, evaluations, risk controls, and changes." }),
  c({ ...legal, id: "EUAIA-HR-04", name: "Automatic record-keeping", objective: "The system automatically records events needed to trace operation, identify risk situations, and support post-market monitoring.", category: "High-Risk Requirements", tierMinimum: 2, pillars: ["security", "governance", "compliance"], testType: "config_check", evaluationRuleId: "adapter.monitoring", severity: "critical", section: "Article 12", evidenceProcedureIds: ["adapter-monitoring-summary", "artifact-audit-log-sample"], remediationId: "eu-automatic-logging", remediation: "Capture tamper-resistant operational, decision, input, retrieval, override, and incident events with defined retention." }),
  c({ ...legal, id: "EUAIA-HR-05", name: "Instructions and transparency", objective: "Deployers receive accurate instructions describing purpose, performance, limits, risks, human oversight, maintenance, and required input data.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.instructions-for-use", severity: "high", section: "Article 13", evidenceProcedureIds: ["document-instructions-for-use", "document-system-card"], remediationId: "eu-instructions", remediation: "Publish version-specific instructions covering capabilities, limitations, foreseeable misuse, oversight, logging, and maintenance." }),
  c({ ...legal, id: "EUAIA-HR-06", name: "Human oversight", objective: "Authorized people can understand relevant system behavior, detect anomalies, avoid automation bias, override outputs, and stop operation.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.human-oversight", severity: "critical", section: "Article 14", evidenceProcedureIds: ["document-human-oversight", "artifact-override-test"], remediationId: "eu-human-oversight", remediation: "Define trained oversight roles, meaningful review points, override and stop controls, and automation-bias mitigations." }),
  c({ ...legal, id: "EUAIA-HR-07", name: "Accuracy, robustness, and cybersecurity", objective: "Accuracy, resilience, security, error handling, and relevant metrics are defined, tested, monitored, and communicated.", category: "High-Risk Requirements", tierMinimum: 1, pillars: ["trust", "security"], testType: "adversarial_probe", evaluationRuleId: "probe.combined-rag-safety", severity: "critical", section: "Article 15", evidenceProcedureIds: ["probe-grounding", "probe-prompt-injection", "probe-sensitive-disclosure"], remediationId: "eu-accuracy-security", remediation: "Set measurable performance and security thresholds, test foreseeable attacks and errors, and monitor degradation." }),
  c({ ...legal, id: "EUAIA-PM-01", name: "Post-market monitoring", objective: "Providers systematically collect, analyze, and act on performance and risk information throughout the system lifetime.", category: "Post-Market", tierMinimum: 2, pillars: ["governance", "trust", "compliance"], testType: "config_check", evaluationRuleId: "adapter.monitoring", severity: "high", section: "Article 72", evidenceProcedureIds: ["adapter-monitoring-summary", "document-post-market-plan"], remediationId: "eu-post-market", remediation: "Operate a documented post-market monitoring plan linked to incidents, complaints, drift, corrective actions, and updates." }),
  c({ ...legal, id: "EUAIA-PM-02", name: "Serious incident reporting", objective: "Serious incidents are recognized, investigated, corrected, documented, and reported within applicable requirements.", category: "Post-Market", tierMinimum: 3, pillars: ["security", "governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.serious-incident", severity: "critical", section: "Article 73", evidenceProcedureIds: ["document-incident-runbook", "artifact-incident-exercise"], remediationId: "eu-serious-incident", remediation: "Add AI Act serious-incident classification, authority notification, investigation, and corrective-action steps to incident response." }),
  c({ ...legal, id: "EUAIA-PROV-02", name: "Documentation and log retention", objective: "Technical documentation, quality records, declarations, certificates, and automatically generated logs are retained for applicable periods and remain available to authorities.", category: "Provider Duties", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.eu-record-retention", severity: "high", section: "Articles 18 and 19", evidenceProcedureIds: ["document-record-retention", "artifact-document-retention", "artifact-audit-log-sample"], remediationId: "eu-record-retention", remediation: "Define and enforce retention, integrity, availability, and authority-access requirements for mandated records and logs." }),
];

export const euAiActPack: FrameworkPack = validateFrameworkPack({
  manifest: { id: "eu_ai_act", release: "2026.10-draft.2", status: "draft", assuranceLevel: "readiness", sourceVersion: "Regulation (EU) 2024/1689", publishedAt: "2026-07-28", contentHash: contentHashForControls(controls), note: "Readiness pack limited to the obligations ARQ Governance can verify, assessed without scope questions. Effective-date logic must be confirmed for each assessment." },
  standard: { id: "eu_ai_act", shortName: "EU AI Act", name: "European Union Artificial Intelligence Act", version: "Regulation (EU) 2024/1689", kind: "Mandatory", jurisdiction: "European Union", description: "High-risk, transparency, deployer, and post-market readiness.", reportFormat: "EU AI Act Applicability and Readiness Report", scoringMethod: "Applicable legal-obligation coverage with critical-control overrides", passThreshold: "No failed applicable mandatory controls; legal review required for a compliance conclusion", officialReference: source },
  controls,
});
