import { contentHashForControls, createPackControl, validateFrameworkPack, type FrameworkPack, type PackControlInput } from "./schema";

const source = {
  authority: "EUR-Lex",
  title: "Regulation (EU) 2024/1689 — Artificial Intelligence Act",
  url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en",
  status: "current" as const,
  note: "Official Journal text. Applicability and enforcement dates must be evaluated as of the assessment date.",
};
const c = (input: PackControlInput) => createPackControl(input, source);
const legal = { mappingType: "official_requirement" as const };

/* Every obligation applies to every assessed system: the pack asks no scope
   questions, so role- and risk-specific articles are reported rather than ruled out. */
const controls = [
  c({ ...legal, id: "EUAIA-PR-01", name: "Prohibited-practice screening", objective: "The use case is screened against prohibited practices and controls prevent prohibited deployment or operation.", category: "Prohibited Practices", tierMinimum: 3, pillars: ["trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.prohibited-practices", severity: "critical", section: "Article 5", evidenceProcedureIds: ["document-prohibited-practice-screening", "artifact-use-case-controls"], remediationId: "prohibited-practice-gate", remediation: "Introduce a mandatory legal and ethics gate that blocks prohibited use cases and circumvention." }),
  c({ ...legal, id: "EUAIA-GOV-01", name: "AI literacy", objective: "Personnel and others operating AI on the organization's behalf have sufficient literacy for their role, context, and affected persons.", category: "Governance", tierMinimum: 3, pillars: ["governance", "trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.training", severity: "high", section: "Article 4", evidenceProcedureIds: ["document-training-program", "artifact-training-completion"], remediationId: "eu-ai-literacy", remediation: "Provide role- and context-specific AI literacy training and retain completion and effectiveness evidence." }),
  c({ ...legal, id: "EUAIA-HR-01", name: "Risk management system", objective: "High-risk AI risks are identified, analyzed, evaluated, treated, tested, and reviewed throughout the lifecycle.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["governance", "trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.risk-management-system", severity: "critical", section: "Article 9", evidenceProcedureIds: ["document-risk-register", "document-risk-treatment", "artifact-test-plan"], remediationId: "eu-risk-management", remediation: "Establish a continuous high-risk AI risk management process with testing and residual-risk acceptance." }),
  c({ ...legal, id: "EUAIA-HR-02", name: "Data and data governance", objective: "Training, validation, testing, and retrieval data are governed for relevance, representativeness, quality, provenance, bias, and appropriate scope.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["data_protection", "trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.data-governance", severity: "critical", section: "Article 10", evidenceProcedureIds: ["artifact-data-lineage", "artifact-rag-corpus-manifest", "artifact-bias-evaluation"], remediationId: "eu-data-governance", remediation: "Implement governed datasets and corpus manifests with provenance, quality, bias, authorization, and limitation records." }),
  c({ ...legal, id: "EUAIA-HR-03", name: "Technical documentation", objective: "Technical documentation demonstrates system purpose, design, capabilities, limits, testing, risks, controls, and lifecycle changes.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.technical-documentation", severity: "critical", section: "Article 11 and Annex IV", evidenceProcedureIds: ["document-system-card", "artifact-technical-file"], remediationId: "eu-technical-file", remediation: "Maintain an Annex IV-aligned technical file linked to versions, evaluations, risk controls, and changes." }),
  c({ ...legal, id: "EUAIA-HR-04", name: "Automatic record-keeping", objective: "The system automatically records events needed to trace operation, identify risk situations, and support post-market monitoring.", category: "High-Risk Requirements", tierMinimum: 2, pillars: ["security", "governance", "compliance"], testType: "config_check", evaluationRuleId: "adapter.monitoring", severity: "critical", section: "Article 12", evidenceProcedureIds: ["adapter-monitoring-summary", "artifact-audit-log-sample"], remediationId: "eu-automatic-logging", remediation: "Capture tamper-resistant operational, decision, input, retrieval, override, and incident events with defined retention." }),
  c({ ...legal, id: "EUAIA-HR-05", name: "Instructions and transparency", objective: "Deployers receive accurate instructions describing purpose, performance, limits, risks, human oversight, maintenance, and required input data.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.instructions-for-use", severity: "high", section: "Article 13", evidenceProcedureIds: ["document-instructions-for-use", "document-system-card"], remediationId: "eu-instructions", remediation: "Publish version-specific instructions covering capabilities, limitations, foreseeable misuse, oversight, logging, and maintenance." }),
  c({ ...legal, id: "EUAIA-HR-06", name: "Human oversight", objective: "Authorized people can understand relevant system behavior, detect anomalies, avoid automation bias, override outputs, and stop operation.", category: "High-Risk Requirements", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.human-oversight", severity: "critical", section: "Article 14", evidenceProcedureIds: ["document-human-oversight", "artifact-override-test"], remediationId: "eu-human-oversight", remediation: "Define trained oversight roles, meaningful review points, override and stop controls, and automation-bias mitigations." }),
  c({ ...legal, id: "EUAIA-HR-07", name: "Accuracy, robustness, and cybersecurity", objective: "Accuracy, resilience, security, error handling, and relevant metrics are defined, tested, monitored, and communicated.", category: "High-Risk Requirements", tierMinimum: 1, pillars: ["trust", "security"], testType: "adversarial_probe", evaluationRuleId: "probe.combined-rag-safety", severity: "critical", section: "Article 15", evidenceProcedureIds: ["probe-grounding", "probe-prompt-injection", "probe-sensitive-disclosure"], remediationId: "eu-accuracy-security", remediation: "Set measurable performance and security thresholds, test foreseeable attacks and errors, and monitor degradation." }),
  c({ ...legal, id: "EUAIA-DEP-01", name: "Deployer operational controls", objective: "Deployers follow instructions, assign competent oversight, control relevant input data, monitor operation, and preserve required logs.", category: "Deployer Duties", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.deployer-controls", severity: "critical", section: "Article 26", evidenceProcedureIds: ["document-deployer-procedure", "artifact-operational-records"], remediationId: "eu-deployer-controls", remediation: "Create operational procedures for instructions, input data, oversight, monitoring, log retention, worker notice, and incident escalation." }),
  c({ ...legal, id: "EUAIA-DEP-02", name: "Fundamental rights impact assessment", objective: "Applicable public-sector and essential-service deployments complete and maintain a fundamental rights impact assessment before use.", category: "Deployer Duties", tierMinimum: 3, pillars: ["trust", "compliance", "governance"], testType: "document_verify", evaluationRuleId: "artifact.fria", severity: "critical", section: "Article 27", evidenceProcedureIds: ["document-fundamental-rights-impact", "document-stakeholder-record"], remediationId: "eu-fria", remediation: "Complete the required impact assessment, identify affected groups and mitigations, and update it after material changes." }),
  c({ ...legal, id: "EUAIA-TR-01", name: "AI interaction transparency", objective: "People are informed when interacting directly with an AI system unless an applicable exception is documented.", category: "Transparency", tierMinimum: 1, pillars: ["trust", "compliance"], testType: "adversarial_probe", evaluationRuleId: "probe.ai-disclosure", severity: "high", section: "Article 50(1)", evidenceProcedureIds: ["probe-ai-disclosure", "document-ai-transparency"], remediationId: "eu-ai-disclosure", remediation: "Provide timely, accessible AI interaction disclosure and document any relied-upon exception." }),
  c({ ...legal, id: "EUAIA-PM-01", name: "Post-market monitoring", objective: "Providers systematically collect, analyze, and act on performance and risk information throughout the system lifetime.", category: "Post-Market", tierMinimum: 2, pillars: ["governance", "trust", "compliance"], testType: "config_check", evaluationRuleId: "adapter.monitoring", severity: "high", section: "Article 72", evidenceProcedureIds: ["adapter-monitoring-summary", "document-post-market-plan"], remediationId: "eu-post-market", remediation: "Operate a documented post-market monitoring plan linked to incidents, complaints, drift, corrective actions, and updates." }),
  c({ ...legal, id: "EUAIA-PM-02", name: "Serious incident reporting", objective: "Serious incidents are recognized, investigated, corrected, documented, and reported within applicable requirements.", category: "Post-Market", tierMinimum: 3, pillars: ["security", "governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.serious-incident", severity: "critical", section: "Article 73", evidenceProcedureIds: ["document-incident-runbook", "artifact-incident-exercise"], remediationId: "eu-serious-incident", remediation: "Add AI Act serious-incident classification, authority notification, investigation, and corrective-action steps to incident response." }),
  c({ ...legal, id: "EUAIA-PROV-01", name: "Provider quality management system", objective: "The provider operates a documented quality management system covering compliance strategy, design, testing, data, records, accountability, suppliers, incidents, and post-market monitoring.", category: "Provider Duties", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.quality-management", severity: "critical", section: "Articles 16(c) and 17", evidenceProcedureIds: ["document-quality-management-system", "artifact-quality-records"], remediationId: "eu-ai-qms", remediation: "Establish an AI Act quality management system with controlled procedures, records, responsibilities, and lifecycle oversight." }),
  c({ ...legal, id: "EUAIA-PROV-02", name: "Documentation and log retention", objective: "Technical documentation, quality records, declarations, certificates, and automatically generated logs are retained for applicable periods and remain available to authorities.", category: "Provider Duties", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.eu-record-retention", severity: "high", section: "Articles 18 and 19", evidenceProcedureIds: ["document-record-retention", "artifact-document-retention", "artifact-audit-log-sample"], remediationId: "eu-record-retention", remediation: "Define and enforce retention, integrity, availability, and authority-access requirements for mandated records and logs." }),
  c({ ...legal, id: "EUAIA-PROV-03", name: "Corrective actions and authority cooperation", objective: "Non-conformity triggers corrective action, withdrawal, disablement or recall as appropriate, notification, and cooperation with competent authorities.", category: "Provider Duties", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.corrective-action", severity: "critical", section: "Articles 20 and 21", evidenceProcedureIds: ["document-corrective-action", "artifact-recall-exercise"], remediationId: "eu-corrective-action", remediation: "Create tested non-conformity, corrective-action, notification, withdrawal, recall, and authority-cooperation procedures." }),
  c({ ...legal, id: "EUAIA-IMP-01", name: "Importer verification", objective: "Importers verify conformity assessment, documentation, CE marking, provider identification, and representative appointment before placing high-risk AI on the market.", category: "Value Chain Duties", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.importer-verification", severity: "critical", section: "Article 23", evidenceProcedureIds: ["document-importer-checklist", "artifact-conformity-records"], remediationId: "eu-importer-verification", remediation: "Implement a pre-market importer verification and non-conformity escalation checklist." }),
  c({ ...legal, id: "EUAIA-DIST-01", name: "Distributor verification", objective: "Distributors verify required markings, documentation, instructions, and provider/importer compliance before making high-risk AI available.", category: "Value Chain Duties", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.distributor-verification", severity: "high", section: "Article 24", evidenceProcedureIds: ["document-distributor-checklist", "artifact-conformity-records"], remediationId: "eu-distributor-verification", remediation: "Implement distribution checks, storage and transport safeguards, and non-conformity escalation." }),
  c({ ...legal, id: "EUAIA-CONF-01", name: "Conformity assessment", objective: "The provider completes the applicable conformity assessment before placing a high-risk AI system on the market or putting it into service.", category: "Conformity", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.conformity-assessment", severity: "critical", section: "Article 43", evidenceProcedureIds: ["document-conformity-assessment", "artifact-conformity-records"], remediationId: "eu-conformity-assessment", remediation: "Determine and complete the applicable conformity route and retain the supporting technical and quality evidence." }),
  c({ ...legal, id: "EUAIA-CONF-02", name: "EU declaration and CE marking", objective: "The provider draws up the EU declaration of conformity and applies required CE marking before market placement or service.", category: "Conformity", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.eu-declaration", severity: "critical", section: "Articles 47 and 48", evidenceProcedureIds: ["document-eu-declaration", "artifact-ce-marking"], remediationId: "eu-declaration-marking", remediation: "Create and maintain the declaration of conformity and apply required marking linked to the assessed version." }),
  c({ ...legal, id: "EUAIA-CONF-03", name: "EU database registration", objective: "The provider or applicable public deployer registers required system, role, use, and impact information and keeps it current.", category: "Conformity", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.eu-registration", severity: "high", section: "Article 49 and Annex VIII", evidenceProcedureIds: ["document-eu-registration", "artifact-registration-record"], remediationId: "eu-database-registration", remediation: "Complete applicable EU database registration before use or market placement and maintain current entries." }),
  c({ ...legal, id: "EUAIA-GPAI-01", name: "GPAI provider documentation and downstream information", objective: "A GPAI provider maintains technical documentation and supplies downstream providers with information needed to understand capabilities, limits, and compliance.", category: "GPAI", tierMinimum: 3, pillars: ["governance", "trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.gpai-documentation", severity: "critical", section: "Article 53(1)(a)–(b) and Annexes XI–XII", evidenceProcedureIds: ["document-gpai-technical-documentation", "artifact-downstream-information"], remediationId: "gpai-documentation", remediation: "Maintain GPAI technical documentation and a controlled downstream information package for integrating providers." }),
  c({ ...legal, id: "EUAIA-GPAI-02", name: "GPAI copyright and training-content transparency", objective: "The GPAI provider maintains a copyright-compliance policy and publishes the required sufficiently detailed training-content summary.", category: "GPAI", tierMinimum: 3, pillars: ["governance", "compliance", "data_protection"], testType: "document_verify", evaluationRuleId: "artifact.gpai-copyright", severity: "high", section: "Article 53(1)(c)–(d)", evidenceProcedureIds: ["document-copyright-policy", "artifact-training-content-summary"], remediationId: "gpai-copyright-transparency", remediation: "Implement copyright compliance controls and publish the prescribed training-content summary." }),
];

export const euAiActPack: FrameworkPack = validateFrameworkPack({
  manifest: { id: "eu_ai_act", release: "2026.10-draft.1", status: "draft", assuranceLevel: "readiness", sourceVersion: "Regulation (EU) 2024/1689", publishedAt: "2026-07-28", contentHash: contentHashForControls(controls), note: "Full-scope readiness pack: every obligation is assessed without scope questions. Effective-date logic must be confirmed for each assessment." },
  standard: { id: "eu_ai_act", shortName: "EU AI Act", name: "European Union Artificial Intelligence Act", version: "Regulation (EU) 2024/1689", kind: "Mandatory", jurisdiction: "European Union", description: "Prohibited-practice, high-risk, transparency, deployer, and post-market readiness.", reportFormat: "EU AI Act Applicability and Readiness Report", scoringMethod: "Applicable legal-obligation coverage with critical-control overrides", passThreshold: "No failed applicable mandatory controls; legal review required for a compliance conclusion", officialReference: source },
  controls,
});
