import { contentHashForControls, createPackControl, validateFrameworkPack, type FrameworkPack } from "./schema";

const source = {
  authority: "U.S. Department of Health and Human Services",
  title: "HIPAA Privacy, Security, and Breach Notification Rules",
  url: "https://www.hhs.gov/hipaa/for-professionals/index.html",
  status: "current" as const,
  note: "Current HIPAA rules. The 2025 Security Rule NPRM is intentionally excluded from compliance scoring.",
};

const control = (
  input: Parameters<typeof createPackControl>[0],
) => createPackControl(input, source);

/* Every safeguard listed applies to every assessed system and the pack asks no
   scope questions. It lists only rules a Tier 3 run can reach a verdict on; PHI use
   policy, individual rights, contingency planning, periodic evaluation, physical and
   media safeguards, breach response, policy documentation and sanctions are out of
   scope. */
const controls = [
  control({
    id: "HIPAA-APP-02",
    name: "PHI and ePHI data-flow inventory",
    objective: "PHI and ePHI entering, leaving, and persisting in the RAG system are inventoried by source, purpose, recipient, and location.",
    category: "Applicability",
    tierMinimum: 3,
    pillars: ["data_protection", "governance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.data-flow",
    severity: "critical",
    section: "45 CFR §§160.103 and 164.306(a)",
    evidenceProcedureIds: ["artifact-data-flow", "artifact-rag-corpus-manifest"],
    remediationId: "phi-data-flow",
    remediation: "Create and approve a PHI/ePHI data-flow and RAG corpus inventory, including subprocessors and storage locations.",
  }),
  control({
    id: "HIPAA-PR-02",
    name: "Minimum necessary",
    objective: "Retrieval, prompt construction, model context, logging, and output disclosure are limited to the minimum PHI necessary for the purpose.",
    category: "Privacy Rule",
    tierMinimum: 2,
    pillars: ["data_protection", "compliance"],
    testType: "config_check",
    evaluationRuleId: "adapter.audit",
    severity: "critical",
    section: "45 CFR §§164.502(b) and 164.514(d)",
    evidenceProcedureIds: ["adapter-audit-configuration", "artifact-rag-access-policy"],
    remediationId: "minimum-necessary-rag",
    remediation: "Apply purpose-scoped retrieval filters, field-level minimization, prompt redaction, and output controls for PHI.",
  }),
  control({
    id: "HIPAA-PR-03",
    name: "Business associate safeguards",
    objective: "Vendors that handle PHI, including model, hosting, observability, and vector-database providers, are covered by appropriate business-associate arrangements.",
    category: "Privacy Rule",
    tierMinimum: 3,
    pillars: ["governance", "compliance", "data_protection"],
    testType: "document_verify",
    evaluationRuleId: "artifact.business-associate-agreements",
    severity: "critical",
    section: "45 CFR §§164.502(e) and 164.504(e)",
    evidenceProcedureIds: ["document-business-associate-inventory", "document-vendor-contracts"],
    remediationId: "baa-coverage",
    remediation: "Inventory PHI-handling vendors, obtain required BAAs, and prohibit PHI transfer to vendors that are not contractually authorized.",
  }),
  control({
    id: "HIPAA-PR-05",
    name: "Notice and transparency",
    objective: "Applicable privacy notices accurately describe material AI-assisted PHI practices and available individual rights.",
    category: "Privacy Rule",
    tierMinimum: 3,
    pillars: ["trust", "compliance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.privacy-notice",
    severity: "medium",
    section: "45 CFR §164.520",
    evidenceProcedureIds: ["document-privacy-notice", "document-ai-transparency"],
    remediationId: "privacy-notice-update",
    remediation: "Review whether AI-assisted processing changes described privacy practices and update notices and user disclosures where required.",
  }),
  control({
    id: "HIPAA-S-01",
    name: "Security risk analysis",
    objective: "A documented, system-specific risk analysis identifies threats, vulnerabilities, likelihood, impact, and existing safeguards for ePHI.",
    category: "Administrative Safeguards",
    tierMinimum: 3,
    pillars: ["security", "governance", "compliance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.security-risk-analysis",
    severity: "critical",
    section: "45 CFR §164.308(a)(1)(ii)(A)",
    evidenceProcedureIds: ["document-security-risk-analysis", "artifact-threat-model"],
    remediationId: "hipaa-risk-analysis",
    remediation: "Complete and approve an ePHI risk analysis covering the chatbot, retrieval pipeline, model provider, vector store, logs, and administrators.",
  }),
  control({
    id: "HIPAA-S-02",
    name: "Risk management",
    objective: "Identified ePHI risks have owners, treatment decisions, target dates, and verified residual-risk acceptance.",
    category: "Administrative Safeguards",
    tierMinimum: 3,
    pillars: ["security", "governance", "compliance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.risk-treatment",
    severity: "critical",
    section: "45 CFR §164.308(a)(1)(ii)(B)",
    evidenceProcedureIds: ["document-risk-register", "document-risk-treatment"],
    remediationId: "risk-treatment-plan",
    remediation: "Create a tracked treatment plan for material ePHI risks and require documented approval of residual risk.",
  }),
  control({
    id: "HIPAA-S-03",
    name: "Assigned security responsibility",
    objective: "A named security official is accountable for policies and safeguards protecting ePHI in the assessed system.",
    category: "Administrative Safeguards",
    tierMinimum: 3,
    pillars: ["governance", "compliance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.security-responsibility",
    severity: "high",
    section: "45 CFR §164.308(a)(2)",
    evidenceProcedureIds: ["document-role-assignment", "document-security-charter"],
    remediationId: "assign-security-official",
    remediation: "Formally assign responsibility and authority for the system's ePHI security program.",
  }),
  control({
    id: "HIPAA-S-04",
    name: "Workforce and information access management",
    objective: "Access to ePHI is authorized by role, provisioned using least privilege, reviewed, and removed promptly.",
    category: "Administrative Safeguards",
    tierMinimum: 2,
    pillars: ["security", "governance"],
    testType: "config_check",
    evaluationRuleId: "adapter.audit",
    severity: "critical",
    section: "45 CFR §§164.308(a)(3) and 164.308(a)(4)",
    evidenceProcedureIds: ["adapter-audit-configuration", "artifact-access-review"],
    remediationId: "ephi-access-governance",
    remediation: "Implement role-based authorization, joiner/mover/leaver controls, and periodic ePHI entitlement reviews.",
  }),
  control({
    id: "HIPAA-S-05",
    name: "Security awareness and training",
    objective: "Workforce members with system access receive role-appropriate security and PHI handling training.",
    category: "Administrative Safeguards",
    tierMinimum: 3,
    pillars: ["security", "governance", "compliance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.training",
    severity: "high",
    section: "45 CFR §164.308(a)(5)",
    evidenceProcedureIds: ["document-training-program", "artifact-training-completion"],
    remediationId: "hipaa-ai-training",
    remediation: "Add role-specific training for PHI in prompts, retrieval sources, model outputs, logs, exports, and incident reporting.",
  }),
  control({
    id: "HIPAA-S-06",
    name: "Security incident procedures",
    objective: "Security incidents involving ePHI can be identified, contained, investigated, mitigated, documented, and escalated.",
    category: "Administrative Safeguards",
    tierMinimum: 2,
    pillars: ["security", "compliance"],
    testType: "config_check",
    evaluationRuleId: "adapter.monitoring",
    severity: "critical",
    section: "45 CFR §164.308(a)(6)",
    evidenceProcedureIds: ["adapter-monitoring-summary", "document-incident-runbook"],
    remediationId: "ephi-incident-response",
    remediation: "Integrate AI/RAG events into incident detection and test an ePHI incident response runbook.",
  }),
  control({
    id: "HIPAA-T-01",
    name: "Unique access and emergency access",
    objective: "Systems handling ePHI enforce unique identities, appropriate access authorization, and controlled emergency access.",
    category: "Technical Safeguards",
    tierMinimum: 2,
    pillars: ["security", "data_protection"],
    testType: "config_check",
    evaluationRuleId: "adapter.audit",
    severity: "critical",
    section: "45 CFR §164.312(a)",
    evidenceProcedureIds: ["adapter-audit-configuration", "artifact-emergency-access"],
    remediationId: "unique-ephi-access",
    remediation: "Replace shared identities, enforce least privilege and session controls, and document emergency access.",
  }),
  control({
    id: "HIPAA-T-02",
    name: "Audit controls",
    objective: "Activity involving ePHI is recorded with sufficient identity, action, object, time, and outcome information for review.",
    category: "Technical Safeguards",
    tierMinimum: 2,
    pillars: ["security", "compliance"],
    testType: "config_check",
    evaluationRuleId: "adapter.monitoring",
    severity: "critical",
    section: "45 CFR §164.312(b)",
    evidenceProcedureIds: ["adapter-monitoring-summary", "artifact-audit-log-sample"],
    remediationId: "ephi-audit-logging",
    remediation: "Log PHI retrieval, administrative changes, exports, authentication, policy decisions, and security-relevant model interactions.",
  }),
  control({
    id: "HIPAA-T-03",
    name: "Integrity protections",
    objective: "Controls detect and prevent improper alteration or destruction of ePHI and RAG source content.",
    category: "Technical Safeguards",
    tierMinimum: 3,
    pillars: ["security", "trust", "data_protection"],
    testType: "document_verify",
    evaluationRuleId: "artifact.integrity-controls",
    severity: "critical",
    section: "45 CFR §164.312(c)",
    evidenceProcedureIds: ["artifact-rag-corpus-manifest", "artifact-integrity-verification"],
    remediationId: "ephi-integrity",
    remediation: "Use controlled ingestion, provenance, checksums, approvals, backups, and anomaly detection for ePHI and indexed content.",
  }),
  control({
    id: "HIPAA-T-04",
    name: "Person or entity authentication",
    objective: "The system verifies that every person or service requesting ePHI access is the claimed identity.",
    category: "Technical Safeguards",
    tierMinimum: 2,
    pillars: ["security"],
    testType: "config_check",
    evaluationRuleId: "adapter.audit",
    severity: "critical",
    section: "45 CFR §164.312(d)",
    evidenceProcedureIds: ["adapter-audit-configuration", "artifact-authentication-policy"],
    remediationId: "ephi-authentication",
    remediation: "Require strong user and workload authentication, protect service credentials, and reject anonymous PHI access.",
  }),
  control({
    id: "HIPAA-T-05",
    name: "Transmission security",
    objective: "ePHI transmitted between users, application services, model providers, retrieval stores, and monitoring systems is protected against unauthorized access and alteration.",
    category: "Technical Safeguards",
    tierMinimum: 3,
    pillars: ["security", "data_protection"],
    testType: "document_verify",
    evaluationRuleId: "artifact.transmission-security",
    severity: "critical",
    section: "45 CFR §164.312(e)",
    evidenceProcedureIds: ["artifact-network-configuration", "artifact-encryption-configuration"],
    remediationId: "ephi-transmission-security",
    remediation: "Enforce authenticated encryption for ePHI flows and document exceptions, certificate management, and endpoint trust.",
  }),
  control({
    id: "HIPAA-S-10",
    name: "Information-system activity review",
    objective: "Audit logs, access reports, and security incident records involving ePHI are reviewed at a documented cadence.",
    category: "Administrative Safeguards",
    tierMinimum: 2,
    pillars: ["security", "compliance"],
    testType: "config_check",
    evaluationRuleId: "adapter.monitoring",
    severity: "critical",
    section: "45 CFR §164.308(a)(1)(ii)(D)",
    evidenceProcedureIds: ["adapter-monitoring-summary", "artifact-log-review-records"],
    remediationId: "ephi-activity-review",
    remediation: "Assign recurring review of access, audit, exception, and incident records with documented follow-up.",
  }),
  control({
    id: "HIPAA-S-11",
    name: "Workforce authorization and termination",
    objective: "Workforce access to ePHI is authorized, supervised, modified, and terminated through controlled procedures.",
    category: "Administrative Safeguards",
    tierMinimum: 3,
    pillars: ["security", "governance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.workforce-access",
    severity: "critical",
    section: "45 CFR §164.308(a)(3)(ii)",
    evidenceProcedureIds: ["document-workforce-access", "artifact-access-review"],
    remediationId: "workforce-access-lifecycle",
    remediation: "Implement authorization, supervision, clearance, and termination procedures for all ePHI access.",
  }),
  control({
    id: "HIPAA-S-12",
    name: "Password and authentication management",
    objective: "Authentication credentials for ePHI systems are issued, changed, protected, recovered, and revoked through approved procedures.",
    category: "Administrative Safeguards",
    tierMinimum: 2,
    pillars: ["security"],
    testType: "config_check",
    evaluationRuleId: "adapter.audit",
    severity: "critical",
    section: "45 CFR §164.308(a)(5)(ii)(D)",
    evidenceProcedureIds: ["adapter-audit-configuration", "artifact-authentication-policy"],
    remediationId: "credential-management",
    remediation: "Enforce strong authentication, managed secrets, credential rotation, recovery, and immediate revocation.",
  }),
  control({
    id: "HIPAA-S-13",
    name: "Data backup plan",
    objective: "Retrievable exact copies of critical ePHI are maintained and restoration is tested.",
    category: "Administrative Safeguards",
    tierMinimum: 3,
    pillars: ["security", "data_protection"],
    testType: "document_verify",
    evaluationRuleId: "artifact.backup-plan",
    severity: "critical",
    section: "45 CFR §164.308(a)(7)(ii)(A)",
    evidenceProcedureIds: ["document-backup-plan", "artifact-recovery-test"],
    remediationId: "ephi-backup",
    remediation: "Maintain protected, tested backups with recovery objectives and evidence of successful restoration.",
  }),
  control({
    id: "HIPAA-S-14",
    name: "Disaster recovery and emergency mode",
    objective: "The organization can restore ePHI systems and protect critical security processes during emergency operation.",
    category: "Administrative Safeguards",
    tierMinimum: 3,
    pillars: ["security", "governance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.disaster-recovery",
    severity: "critical",
    section: "45 CFR §§164.308(a)(7)(ii)(B)–(C)",
    evidenceProcedureIds: ["document-disaster-recovery", "artifact-continuity-exercise"],
    remediationId: "ephi-disaster-recovery",
    remediation: "Test restoration, emergency operation, communications, and security controls under realistic disruption scenarios.",
  }),
  control({
    id: "HIPAA-PR-06",
    name: "Accounting of disclosures",
    objective: "The organization can identify and provide an accounting of applicable PHI disclosures involving the system.",
    category: "Privacy Rule",
    tierMinimum: 3,
    pillars: ["data_protection", "compliance"],
    testType: "document_verify",
    evaluationRuleId: "artifact.disclosure-accounting",
    severity: "high",
    section: "45 CFR §164.528",
    evidenceProcedureIds: ["document-disclosure-accounting", "artifact-audit-log-sample"],
    remediationId: "phi-disclosure-accounting",
    remediation: "Record applicable disclosures with recipient, purpose, data, date, and response workflow.",
  }),
];

export const hipaaCurrentPack: FrameworkPack = validateFrameworkPack({
  manifest: {
    id: "hipaa",
    release: "2026.10-draft.2",
    status: "draft",
    assuranceLevel: "readiness",
    sourceVersion: "45 CFR Parts 160 and 164 — current rules",
    publishedAt: "2026-07-28",
    contentHash: contentHashForControls(controls),
    note: "Initial ARQ Governance-authored HIPAA readiness pack. It is not legal advice or an OCR compliance determination.",
  },
  standard: {
    id: "hipaa",
    shortName: "HIPAA",
    name: "HIPAA Privacy, Security, and Breach Notification Rules",
    version: "45 CFR Parts 160 and 164 — current rules",
    kind: "Mandatory",
    jurisdiction: "United States",
    description: "Privacy, security, and breach readiness for RAG systems handling PHI or ePHI.",
    reportFormat: "HIPAA Readiness and Evidence Report",
    scoringMethod: "Applicable-control coverage with critical-control overrides",
    passThreshold: "No failed applicable critical controls; complete evidence required for a compliance conclusion",
    officialReference: source,
  },
  controls,
});
