import { contentHashForControls, createPackControl, validateFrameworkPack, type FrameworkPack, type PackControlInput } from "./schema";

const source = {
  authority: "National Institute of Standards and Technology",
  title: "AI Risk Management Framework 1.0 and Generative AI Profile",
  url: "https://www.nist.gov/itl/ai-risk-management-framework",
  status: "under_revision" as const,
  note: "AI RMF 1.0 is voluntary and is currently being revised by NIST.",
};

const c = (input: PackControlInput) => createPackControl(input, source);
const common = {
  applicability: ["all_assessed_ai_systems"],
  mappingType: "official_guidance" as const,
};

const controls = [
  c({ ...common, id: "NIST-GOV-01", name: "AI risk governance policy", objective: "AI risk management policies define accountable roles, authorities, escalation, and review across the system lifecycle.", category: "GOVERN", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.ai-governance", severity: "high", section: "AI RMF GOVERN 1.1–1.7", evidenceProcedureIds: ["document-ai-governance-policy", "document-role-assignment"], remediationId: "ai-governance-policy", remediation: "Approve an AI governance policy with accountable owners, escalation paths, decision rights, and review cadence." }),
  c({ ...common, id: "NIST-GOV-02", name: "Legal and regulatory inventory", objective: "Applicable legal, regulatory, contractual, and policy requirements are identified and maintained for the AI system.", category: "GOVERN", tierMinimum: 3, pillars: ["governance", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.obligations-register", severity: "high", section: "AI RMF GOVERN 1.2 and 1.7", evidenceProcedureIds: ["document-regulatory-scope", "document-obligations-register"], remediationId: "obligations-register", remediation: "Maintain an applicability register with owners, effective dates, evidence obligations, and change monitoring." }),
  c({ ...common, id: "NIST-GOV-03", name: "AI risk culture and training", objective: "Personnel receive role-appropriate training and can raise AI risk concerns without suppressing independent challenge.", category: "GOVERN", tierMinimum: 3, pillars: ["governance", "trust"], testType: "document_verify", evaluationRuleId: "artifact.training", severity: "medium", section: "AI RMF GOVERN 2.1–2.3", evidenceProcedureIds: ["document-training-program", "artifact-training-completion"], remediationId: "ai-risk-training", remediation: "Provide role-based AI risk training and establish protected escalation and challenge mechanisms." }),
  c({ ...common, id: "NIST-GOV-04", name: "Third-party AI risk", objective: "Model, data, hosting, retrieval, and monitoring suppliers are assessed before use and monitored throughout the relationship.", category: "GOVERN", tierMinimum: 3, pillars: ["governance", "security"], testType: "document_verify", evaluationRuleId: "artifact.third-party-risk", severity: "high", section: "AI RMF GOVERN 6.1–6.2", evidenceProcedureIds: ["document-vendor-contracts", "document-supplier-assessment"], remediationId: "ai-supplier-risk", remediation: "Create supplier due-diligence, contractual-control, concentration-risk, and ongoing-monitoring requirements." }),
  c({ ...common, id: "NIST-MAP-01", name: "Intended purpose and context", objective: "The intended purpose, users, affected parties, operating context, assumptions, and prohibited uses are documented.", category: "MAP", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.system-context", severity: "high", section: "AI RMF MAP 1.1–1.6", evidenceProcedureIds: ["document-system-card", "document-use-case-scope"], remediationId: "system-context", remediation: "Document intended and prohibited uses, affected groups, dependencies, assumptions, and deployment context." }),
  c({ ...common, id: "NIST-MAP-02", name: "Stakeholder and impact analysis", objective: "Potential benefits and harms to individuals, groups, organizations, and society are identified with stakeholder input.", category: "MAP", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.impact-assessment", severity: "high", section: "AI RMF MAP 2.1–2.3", evidenceProcedureIds: ["document-impact-assessment", "document-stakeholder-record"], remediationId: "stakeholder-impact", remediation: "Perform a documented impact assessment and involve representative affected stakeholders." }),
  c({ ...common, id: "NIST-MAP-03", name: "Data and RAG context", objective: "Training, evaluation, prompt, retrieval, and output data have documented provenance, suitability, limitations, and governance.", category: "MAP", tierMinimum: 3, pillars: ["data_protection", "trust"], testType: "document_verify", evaluationRuleId: "artifact.data-governance", severity: "critical", section: "AI RMF MAP 2.3 and MAP 3.1–3.5; NIST AI 600-1 Data Privacy and Data Integrity", evidenceProcedureIds: ["artifact-rag-corpus-manifest", "artifact-data-lineage"], remediationId: "rag-data-governance", remediation: "Create versioned data and corpus manifests with provenance, authorization, quality, limitations, and change history." }),
  c({ ...common, id: "NIST-MAP-04", name: "Risk prioritization", objective: "Identified AI risks are prioritized using documented likelihood, impact, affected-party, and uncertainty criteria.", category: "MAP", tierMinimum: 3, pillars: ["governance", "trust"], testType: "document_verify", evaluationRuleId: "artifact.risk-register", severity: "high", section: "AI RMF MAP 5.1–5.2", evidenceProcedureIds: ["document-risk-register", "document-risk-methodology"], remediationId: "ai-risk-prioritization", remediation: "Define risk criteria and maintain a prioritized AI risk register with uncertainty and affected-party considerations." }),
  c({ ...common, id: "NIST-MEASURE-01", name: "Groundedness and accuracy evaluation", objective: "The RAG system is evaluated against representative datasets using defined groundedness, accuracy, and citation thresholds.", category: "MEASURE", tierMinimum: 1, pillars: ["trust"], testType: "adversarial_probe", evaluationRuleId: "probe.grounding", severity: "critical", section: "AI RMF MEASURE 2.1–2.13; NIST AI 600-1 Confabulation", evidenceProcedureIds: ["probe-grounding"], remediationId: "groundedness-evaluation", remediation: "Build representative evaluation sets, define thresholds, measure unsupported claims, and track regressions." }),
  c({ ...common, id: "NIST-MEASURE-02", name: "Prompt-injection resilience", objective: "The system resists direct and retrieved-content prompt injection without exposing protected instructions or crossing authorization boundaries.", category: "MEASURE", tierMinimum: 1, pillars: ["security", "trust"], testType: "adversarial_probe", evaluationRuleId: "probe.injection", severity: "critical", section: "NIST AI 600-1 Information Security and Prompt Injection", evidenceProcedureIds: ["probe-prompt-injection"], remediationId: "prompt-injection-controls", remediation: "Layer instruction isolation, content trust labels, tool authorization, retrieval filtering, and adversarial regression tests." }),
  c({ ...common, id: "NIST-MEASURE-03", name: "Sensitive information disclosure", objective: "The system prevents unauthorized disclosure of secrets, personal data, hidden instructions, and restricted retrieved content.", category: "MEASURE", tierMinimum: 1, pillars: ["security", "data_protection"], testType: "adversarial_probe", evaluationRuleId: "probe.disclosure", severity: "critical", section: "NIST AI 600-1 Data Privacy and Information Security", evidenceProcedureIds: ["probe-sensitive-disclosure"], remediationId: "sensitive-output-controls", remediation: "Remove secrets from prompts, enforce retrieval authorization, redact sensitive context, and apply output DLP." }),
  c({ ...common, id: "NIST-MEASURE-04", name: "Bias and adverse-impact evaluation", objective: "Performance and harmful outcomes are evaluated across relevant populations and use contexts using documented limitations.", category: "MEASURE", tierMinimum: 3, pillars: ["trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.bias-evaluation", severity: "high", section: "AI RMF MEASURE 2.5, 2.11 and 2.13", evidenceProcedureIds: ["artifact-bias-evaluation", "document-evaluation-methodology"], remediationId: "bias-evaluation", remediation: "Define relevant groups and harms, test disaggregated outcomes, document uncertainty, and verify mitigation." }),
  c({ ...common, id: "NIST-MEASURE-05", name: "Monitoring and incident detection", objective: "Production monitoring detects safety, security, quality, drift, misuse, and data-integrity events against defined thresholds.", category: "MEASURE", tierMinimum: 2, pillars: ["security", "trust"], testType: "config_check", evaluationRuleId: "adapter.monitoring", severity: "high", section: "AI RMF MEASURE 3.1–3.3", evidenceProcedureIds: ["adapter-monitoring-summary", "artifact-monitor-thresholds"], remediationId: "ai-production-monitoring", remediation: "Monitor quality, safety, security, cost, drift, retrieval health, and anomalous use with owned alerts." }),
  c({ ...common, id: "NIST-MANAGE-01", name: "Risk treatment and acceptance", objective: "AI risks have selected treatment actions, accountable owners, deadlines, verification, and explicit residual-risk decisions.", category: "MANAGE", tierMinimum: 3, pillars: ["governance", "trust"], testType: "document_verify", evaluationRuleId: "artifact.risk-treatment", severity: "critical", section: "AI RMF MANAGE 1.1–1.4", evidenceProcedureIds: ["document-risk-treatment", "document-risk-acceptance"], remediationId: "ai-risk-treatment", remediation: "Assign and track treatments, verify effectiveness, and require accountable residual-risk acceptance." }),
  c({ ...common, id: "NIST-MANAGE-02", name: "Incident response and recovery", objective: "AI incidents can be contained, investigated, communicated, recovered, and used to improve controls.", category: "MANAGE", tierMinimum: 2, pillars: ["security", "governance"], testType: "config_check", evaluationRuleId: "adapter.monitoring", severity: "critical", section: "AI RMF MANAGE 2.3–2.4 and 4.1–4.3", evidenceProcedureIds: ["adapter-monitoring-summary", "document-incident-runbook"], remediationId: "ai-incident-response", remediation: "Integrate AI incidents into response, recovery, disclosure, lessons-learned, and control-update workflows." }),
  c({ ...common, id: "NIST-MANAGE-03", name: "Change and decommissioning decisions", objective: "Material model, data, retrieval, provider, and use changes trigger reassessment, and unsafe systems can be restricted or retired.", category: "MANAGE", tierMinimum: 3, pillars: ["governance", "trust"], testType: "document_verify", evaluationRuleId: "artifact.change-management", severity: "high", section: "AI RMF MANAGE 3.1–3.2", evidenceProcedureIds: ["document-change-policy", "artifact-change-history"], remediationId: "ai-change-control", remediation: "Define material-change triggers, approval gates, rollback criteria, and decommissioning procedures." }),
  c({ ...common, id: "NIST-GOV-05", name: "AI system inventory", objective: "AI systems, models, datasets, retrieval stores, owners, uses, and lifecycle states are inventoried and kept current.", category: "GOVERN", tierMinimum: 3, pillars: ["governance"], testType: "document_verify", evaluationRuleId: "artifact.ai-inventory", severity: "high", section: "AI RMF GOVERN 1.6 and GOVERN 4.1", evidenceProcedureIds: ["document-ai-inventory", "artifact-system-inventory"], remediationId: "ai-system-inventory", remediation: "Maintain a versioned AI inventory linked to owners, purpose, data, dependencies, risk level, and deployment state." }),
  c({ ...common, id: "NIST-GOV-06", name: "Independent challenge and accountability", objective: "Risk decisions and evaluations receive appropriately independent challenge with clear accountability for accepted outcomes.", category: "GOVERN", tierMinimum: 3, pillars: ["governance", "trust"], testType: "document_verify", evaluationRuleId: "artifact.independent-challenge", severity: "high", section: "AI RMF GOVERN 3.1–3.2", evidenceProcedureIds: ["document-assurance-model", "artifact-approval-records"], remediationId: "independent-ai-challenge", remediation: "Separate accountable approval from implementation where practical and retain documented challenge and disposition." }),
  c({ ...common, id: "NIST-GOV-07", name: "Feedback and appeal mechanisms", objective: "Affected users can provide feedback, report harm, contest outcomes, and obtain appropriate human review.", category: "GOVERN", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.feedback-mechanism", severity: "high", section: "AI RMF GOVERN 4.2–4.3", evidenceProcedureIds: ["document-feedback-process", "artifact-appeal-records"], remediationId: "ai-feedback-appeal", remediation: "Provide accessible feedback, complaint, appeal, and human-review routes with tracked resolution." }),
  c({ ...common, id: "NIST-MAP-05", name: "System dependencies and boundaries", objective: "Technical, organizational, human, and third-party dependencies and failure boundaries are mapped.", category: "MAP", tierMinimum: 3, pillars: ["security", "governance"], testType: "document_verify", evaluationRuleId: "artifact.system-boundaries", severity: "high", section: "AI RMF MAP 4.1–4.2", evidenceProcedureIds: ["artifact-architecture-diagram", "document-dependency-inventory"], remediationId: "ai-system-boundaries", remediation: "Map upstream and downstream dependencies, trust boundaries, human roles, and cascading failure modes." }),
  c({ ...common, id: "NIST-MAP-06", name: "Emergent and downstream impacts", objective: "Foreseeable misuse, emergent behavior, downstream use, and cumulative impacts are documented and revisited.", category: "MAP", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.emergent-risk", severity: "high", section: "AI RMF MAP 5.1–5.2", evidenceProcedureIds: ["document-misuse-analysis", "artifact-impact-monitoring"], remediationId: "emergent-risk-analysis", remediation: "Analyze foreseeable misuse and downstream impacts and update the assessment when context or capabilities change." }),
  c({ ...common, id: "NIST-MEASURE-06", name: "Measurement methodology and thresholds", objective: "Metrics, datasets, thresholds, uncertainty, limitations, and evaluation frequency are justified for the mapped risks.", category: "MEASURE", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.measurement-methodology", severity: "high", section: "AI RMF MEASURE 1.1–1.3", evidenceProcedureIds: ["document-evaluation-methodology", "artifact-test-plan"], remediationId: "ai-measurement-method", remediation: "Define validated metrics and thresholds linked to each material risk, including uncertainty and known blind spots." }),
  c({ ...common, id: "NIST-MEASURE-07", name: "Evaluation reproducibility", objective: "Evaluation inputs, versions, configuration, code, and results are reproducible and independently reviewable.", category: "MEASURE", tierMinimum: 3, pillars: ["trust", "governance"], testType: "document_verify", evaluationRuleId: "artifact.evaluation-reproducibility", severity: "high", section: "AI RMF MEASURE 2.1–2.4", evidenceProcedureIds: ["artifact-evaluation-bundle", "artifact-change-history"], remediationId: "reproducible-evaluation", remediation: "Version evaluation data, prompts, code, model settings, thresholds, and result artifacts." }),
  c({ ...common, id: "NIST-MEASURE-08", name: "Privacy risk evaluation", objective: "Privacy risks from prompts, retrieval, memorization, inference, outputs, telemetry, and retained artifacts are evaluated.", category: "MEASURE", tierMinimum: 3, pillars: ["data_protection", "trust"], testType: "document_verify", evaluationRuleId: "artifact.privacy-evaluation", severity: "critical", section: "AI RMF MEASURE 2.10; NIST AI 600-1 Data Privacy", evidenceProcedureIds: ["document-privacy-impact-assessment", "artifact-privacy-tests"], remediationId: "ai-privacy-evaluation", remediation: "Test data minimization, membership and attribute inference exposure, memorization, leakage, and retention controls." }),
  c({ ...common, id: "NIST-MEASURE-09", name: "Explainability and transparency evaluation", objective: "Explanations, sources, notices, and uncertainty communication are evaluated for intended users and decisions.", category: "MEASURE", tierMinimum: 3, pillars: ["trust", "compliance"], testType: "document_verify", evaluationRuleId: "artifact.explainability-evaluation", severity: "high", section: "AI RMF MEASURE 2.9 and 2.13", evidenceProcedureIds: ["artifact-explainability-tests", "document-ai-transparency"], remediationId: "explainability-evaluation", remediation: "Evaluate whether intended users can understand outputs, sources, uncertainty, limitations, and recourse." }),
  c({ ...common, id: "NIST-MANAGE-04", name: "Ongoing risk monitoring", objective: "Risk indicators, incidents, feedback, drift, and changes are monitored and feed updated risk decisions.", category: "MANAGE", tierMinimum: 2, pillars: ["governance", "trust"], testType: "config_check", evaluationRuleId: "adapter.monitoring", severity: "high", section: "AI RMF MANAGE 2.1–2.4", evidenceProcedureIds: ["adapter-monitoring-summary", "artifact-impact-monitoring"], remediationId: "ongoing-ai-risk-monitoring", remediation: "Link production indicators and stakeholder feedback to owned risk review and treatment updates." }),
  c({ ...common, id: "NIST-MANAGE-05", name: "Risk communication", objective: "Material AI risks, limitations, changes, incidents, and residual risk are communicated to relevant internal and external actors.", category: "MANAGE", tierMinimum: 3, pillars: ["governance", "trust"], testType: "document_verify", evaluationRuleId: "artifact.risk-communication", severity: "medium", section: "AI RMF MANAGE 4.1–4.3", evidenceProcedureIds: ["document-risk-communication", "artifact-stakeholder-notices"], remediationId: "ai-risk-communication", remediation: "Define audiences, triggers, content, channels, owners, and evidence for AI risk communications." }),
  c({ ...common, id: "NIST-MANAGE-06", name: "Safe restriction and deactivation", objective: "The organization can restrict, roll back, suspend, or deactivate the system when risk exceeds tolerance.", category: "MANAGE", tierMinimum: 3, pillars: ["security", "governance"], testType: "document_verify", evaluationRuleId: "artifact.safe-shutdown", severity: "critical", section: "AI RMF MANAGE 1.1 and 2.4", evidenceProcedureIds: ["document-safe-shutdown", "artifact-rollback-test"], remediationId: "ai-safe-shutdown", remediation: "Implement tested feature restriction, rollback, suspension, and deactivation procedures with accountable authority." }),
];

export const nistAiRmfPack: FrameworkPack = validateFrameworkPack({
  manifest: { id: "nist_ai_rmf", release: "2026.07-draft.2", status: "draft", assuranceLevel: "readiness", sourceVersion: "AI RMF 1.0 + NIST AI 600-1", publishedAt: "2026-07-28", contentHash: contentHashForControls(controls), note: "Expanded RAG-focused readiness profile; it does not claim NIST endorsement." },
  standard: { id: "nist_ai_rmf", shortName: "NIST AI RMF", name: "NIST Artificial Intelligence Risk Management Framework", version: "AI RMF 1.0 + Generative AI Profile", kind: "Methodological", jurisdiction: "United States / Global", description: "RAG-focused outcomes across Govern, Map, Measure, and Manage.", reportFormat: "NIST AI RMF Readiness Profile", scoringMethod: "Applicable outcome coverage with evidence confidence", passThreshold: "No failed critical outcomes and at least 90% assessed coverage", officialReference: source },
  controls,
});
