import { contentHashForControls, createPackControl, validateFrameworkPack, type FrameworkPack, type PackControlInput } from "./schema";

const source = {
  authority: "OWASP Foundation",
  title: "OWASP Top 10 for LLM Applications 2025",
  url: "https://genai.owasp.org/llm-top-10/",
  status: "current" as const,
  note: "Official OWASP risk taxonomy. GovernAI executes only bounded, authorized procedures.",
};
const c = (input: PackControlInput) => createPackControl(input, source);
const shared = { category: "OWASP LLM Top 10", applicability: ["llm_or_rag_system"], mappingType: "official_guidance" as const };

const controls = [
  c({ ...shared, id: "LLM01", name: "Prompt Injection", objective: "Untrusted direct and retrieved instructions cannot override trusted policy or cross authorization boundaries.", tierMinimum: 1, pillars: ["security", "trust"], testType: "adversarial_probe", evaluationRuleId: "probe.injection", severity: "critical", section: "LLM01:2025 Prompt Injection", evidenceProcedureIds: ["probe-prompt-injection", "probe-indirect-injection", "artifact-tool-permissions"], remediationId: "prompt-injection-controls", remediation: "Isolate instructions, label untrusted content, constrain tools, filter retrieval, and regression-test injection cases." }),
  c({ ...shared, id: "LLM02", name: "Sensitive Information Disclosure", objective: "The system does not disclose secrets, personal data, hidden instructions, or content outside the requester's authorization.", tierMinimum: 1, pillars: ["security", "data_protection"], testType: "adversarial_probe", evaluationRuleId: "probe.disclosure", severity: "critical", section: "LLM02:2025 Sensitive Information Disclosure", evidenceProcedureIds: ["probe-sensitive-disclosure", "artifact-output-dlp", "artifact-rag-access-policy"], remediationId: "sensitive-output-controls", remediation: "Remove secrets from prompts, enforce retrieval authorization, minimize context, and apply output filtering." }),
  c({ ...shared, id: "LLM03", name: "Supply Chain", objective: "Models, datasets, libraries, adapters, prompts, and services have provenance, approved versions, integrity checks, and supplier oversight.", tierMinimum: 3, pillars: ["security", "governance"], testType: "document_verify", evaluationRuleId: "artifact.ai-supply-chain", severity: "high", section: "LLM03:2025 Supply Chain", evidenceProcedureIds: ["artifact-sbom", "artifact-dependency-scan", "document-supplier-assessment", "artifact-model-provenance"], remediationId: "llm-supply-chain", remediation: "Inventory and pin components, verify provenance and integrity, scan dependencies, and monitor suppliers." }),
  c({ ...shared, id: "LLM04", name: "Data and Model Poisoning", objective: "Training, tuning, and retrieval data are authorized, traceable, validated, and monitored for malicious or harmful manipulation.", tierMinimum: 3, pillars: ["security", "trust"], testType: "document_verify", evaluationRuleId: "artifact.corpus-integrity", severity: "critical", section: "LLM04:2025 Data and Model Poisoning", evidenceProcedureIds: ["artifact-rag-corpus-manifest", "artifact-integrity-verification"], remediationId: "corpus-poisoning-controls", remediation: "Use approved sources, signed ingestion, quarantine, anomaly detection, versioning, and rollback." }),
  c({ ...shared, id: "LLM05", name: "Improper Output Handling", objective: "Model output is treated as untrusted before rendering, executing, storing, or passing it to another system.", tierMinimum: 3, pillars: ["security"], testType: "document_verify", evaluationRuleId: "artifact.output-handling", severity: "critical", section: "LLM05:2025 Improper Output Handling", evidenceProcedureIds: ["artifact-output-sink-review", "artifact-security-tests", "artifact-output-encoding", "artifact-schema-validation"], remediationId: "safe-output-handling", remediation: "Apply contextual encoding, schema validation, allowlists, parameterized interfaces, and execution isolation." }),
  c({ ...shared, id: "LLM06", name: "Excessive Agency", objective: "Tools and actions are limited by least privilege, explicit authorization, bounded autonomy, and human approval for consequential operations.", tierMinimum: 3, pillars: ["security", "governance"], testType: "document_verify", evaluationRuleId: "artifact.agent-authority", severity: "critical", section: "LLM06:2025 Excessive Agency", evidenceProcedureIds: ["artifact-tool-permissions", "document-human-oversight"], remediationId: "bounded-agency", remediation: "Minimize tool capabilities, scope identities, validate parameters, add approvals, and provide emergency stop controls." }),
  c({ ...shared, id: "LLM07", name: "System Prompt Leakage", objective: "System prompts contain no secrets or sole-source security controls, and extraction attempts do not expose protected instructions.", tierMinimum: 1, pillars: ["security"], testType: "adversarial_probe", evaluationRuleId: "probe.injection", severity: "high", section: "LLM07:2025 System Prompt Leakage", evidenceProcedureIds: ["probe-system-prompt-disclosure"], remediationId: "prompt-secrecy-boundary", remediation: "Keep secrets outside prompts, enforce controls independently, and detect instruction-extraction patterns." }),
  c({ ...shared, id: "LLM08", name: "Vector and Embedding Weaknesses", objective: "Vector data and retrieval enforce tenant isolation, authorization, provenance, integrity, and appropriate relevance thresholds.", tierMinimum: 3, pillars: ["security", "trust", "data_protection"], testType: "document_verify", evaluationRuleId: "artifact.vector-security", severity: "critical", section: "LLM08:2025 Vector and Embedding Weaknesses", evidenceProcedureIds: ["artifact-vector-configuration", "artifact-rag-corpus-manifest"], remediationId: "vector-security", remediation: "Enforce namespace isolation, metadata authorization, controlled ingestion, retrieval thresholds, and monitoring." }),
  c({ ...shared, id: "LLM09", name: "Misinformation", objective: "The system measures groundedness, communicates uncertainty, provides usable sources, and requires verification for consequential outputs.", tierMinimum: 1, pillars: ["trust"], testType: "adversarial_probe", evaluationRuleId: "probe.grounding", severity: "high", section: "LLM09:2025 Misinformation", evidenceProcedureIds: ["probe-grounding"], remediationId: "misinformation-controls", remediation: "Evaluate factuality and groundedness, show sources and uncertainty, and require human verification for high-impact use." }),
  c({ ...shared, id: "LLM10", name: "Unbounded Consumption", objective: "Token, request, recursion, concurrency, tool, storage, and cost consumption are bounded and monitored.", tierMinimum: 3, pillars: ["security"], testType: "document_verify", evaluationRuleId: "artifact.resource-limits", severity: "high", section: "LLM10:2025 Unbounded Consumption", evidenceProcedureIds: ["artifact-resource-limits", "artifact-rate-limits", "artifact-cost-budgets", "adapter-monitoring-summary"], remediationId: "resource-limits", remediation: "Apply quotas, timeouts, recursion and tool limits, rate controls, budgets, alerts, and graceful degradation." }),
];

export const owaspLlm2025Pack: FrameworkPack = validateFrameworkPack({
  manifest: { id: "owasp_llm_2025", release: "2026.07-draft.2", status: "draft", assuranceLevel: "screening", sourceVersion: "OWASP Top 10 for LLM Applications 2025", publishedAt: "2026-07-28", contentHash: contentHashForControls(controls), note: "Expanded safe-test pack; invasive and denial-of-service procedures remain excluded." },
  standard: { id: "owasp_llm_2025", shortName: "OWASP LLM Top 10", name: "OWASP Top 10 for LLM Applications", version: "2025", kind: "Methodological", jurisdiction: "Global", description: "Ten LLM risk families mapped to bounded probes and artifact review.", reportFormat: "OWASP LLM Security Appendix", scoringMethod: "Risk-family result with evidence confidence", passThreshold: "No failed critical risk family; complete testing requires authorized artifact access", officialReference: source },
  controls,
});
